this.JSON||(this.JSON={});
(function(){function a(a){return 10>a?"0"+a:a}function e(a){k.lastIndex=0;return k.test(a)?'"'+a.replace(k,function(a){var c=n[a];return"string"===typeof c?c:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function c(a,g){var l,t,q,k,n=m,x,u=g[a];u&&("object"===typeof u&&"function"===typeof u.toJSON)&&(u=u.toJSON(a));"function"===typeof h&&(u=h.call(g,a,u));switch(typeof u){case "string":return e(u);case "number":return isFinite(u)?String(u):"null";case "boolean":case "null":return String(u);
case "object":if(!u)return"null";m+=p;x=[];if("[object Array]"===Object.prototype.toString.apply(u)){k=u.length;for(l=0;l<k;l+=1)x[l]=c(l,u)||"null";q=0===x.length?"[]":m?"[\n"+m+x.join(",\n"+m)+"\n"+n+"]":"["+x.join(",")+"]";m=n;return q}if(h&&"object"===typeof h){k=h.length;for(l=0;l<k;l+=1)t=h[l],"string"===typeof t&&(q=c(t,u))&&x.push(e(t)+(m?": ":":")+q)}else for(t in u)Object.hasOwnProperty.call(u,t)&&(q=c(t,u))&&x.push(e(t)+(m?": ":":")+q);q=0===x.length?"{}":m?"{\n"+m+x.join(",\n"+m)+"\n"+
n+"}":"{"+x.join(",")+"}";m=n;return q}}"function"!==typeof Date.prototype.toJSON&&(Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+a(this.getUTCMonth()+1)+"-"+a(this.getUTCDate())+"T"+a(this.getUTCHours())+":"+a(this.getUTCMinutes())+":"+a(this.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()});var g=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
k=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,m,p,n={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},h;"function"!==typeof JSON.stringify&&(JSON.stringify=function(a,e,l){var g;p=m="";if("number"===typeof l)for(g=0;g<l;g+=1)p+=" ";else"string"===typeof l&&(p=l);if((h=e)&&"function"!==typeof e&&("object"!==typeof e||"number"!==typeof e.length))throw Error("JSON.stringify");return c("",{"":a})});
"function"!==typeof JSON.parse&&(JSON.parse=function(a,c){function h(a,e){var g,k,t=a[e];if(t&&"object"===typeof t)for(g in t)Object.hasOwnProperty.call(t,g)&&(k=h(t,g),void 0!==k?t[g]=k:delete t[g]);return c.call(a,e,t)}var e;a=String(a);g.lastIndex=0;g.test(a)&&(a=a.replace(g,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,
"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return e=eval("("+a+")"),"function"===typeof c?h({"":e},""):e;throw new SyntaxError("JSON.parse");})})();"function"!==typeof Date.now&&(Date.now=function(){return(new Date).getTime()});window._previousPureDom=window.puredom;
(function(){var a=function(){return h.puredom.apply(h,arguments)},e={version:"1.1.1",baseAnimationInterval:20,allowCssTransitions:!0,easingMethods:{ease:function(a){return(Math.sin(a*Math.PI-Math.PI/2)+1)/2},"ease-in-out":function(a){return(Math.sin(a*Math.PI-Math.PI/2)+1)/2},"ease-in-out-2":function(a){return this["ease-in-out"](this["ease-in-out"](a))},"ease-in-out-3":function(a){return this["ease-in-out"](this["ease-in-out"](this["ease-in-out"](a)))}}},c=!1,g,k,m=e.constructor,p,n,h={oninit:[],
animationTimes:{fast:150,medium:450,slow:1E3},animationTimeScale:1,registeredEventCount:0,html5elements:"abbr article aside audio canvas datalist details figcaption figure footer header hgroup mark meter nav output progress section summary time video".split(" "),support:{html5:!0,querySelectorAll:!!("querySelectorAll"in document),filters:!1,webkitMultitouch:!!("createTouch"in document)},regex:{css3AutoPrefix:/([\s\;\/\*])(box\-shadow|text\-shadow|border\-radius)\:([^\;]*)(\;|$)/gim,css3VendorPrefix:/\b\-(moz|webkit|ms|o|vendor)\-/gim,
templateFieldToken:/([^\\]?)\{([a-z0-9A-Z\$_\.]+)(\|[^\}]*?)?\}/gm,parseObjectNameFromString:/^\[object ([^\s]+)\]$/gim,autoDetectHTMLContent:/(<[a-z]|&[a-z#0-9]{1,10};)/gim,whitespaceCharacters:/\s/,getNumericCSSValue:/[^0-9\.\-]/gm,getCSSValueUnits:/([a-z]+|%)$/,getNonIntegerCharsSigned:/[^0-9\.\-]/gm,getUpperCaseAlphaChars:/[A-Z]/gm}};navigator.userAgent.match(/\b(iOS|Android|WebOS|iPhone|iPod|iPad)\b/gim)&&(a.allowCssTransitions=!1,a.baseAnimationInterval=50,h.animationTimeScale=1.5);navigator.userAgent.match(/\b(webkit|applewebkit|chrome|chromium|khtml)\b/gim)?
(g="-webkit",k="Webkit"):navigator.userAgent.match(/\bopera\b/gim)?(g="-o",k="O"):navigator.userAgent.match(/\bgecko\b/gim)?(g="-moz",k="Moz"):navigator.userAgent.match(/\bmsie\s*?(8|9|[1-9][0-9]+)\b/gim)?(g="-ms",k="Ms"):navigator.userAgent.match(/\bmsie\s*?[4-8]\b/gim)&&(h.support.filters=!0,h.support.filterProperty="filter");var s=void 0,s=void 0,s=document.createElement("div");s.innerHTML="<nav></nav>";h.support.html5=0<s.childNodes.length;if(!h.support.html5){h.html5frag=document.createDocumentFragment();
for(s=h.html5elements.length;s--;)h.html5frag.createElement(h.html5elements[s]);h.html5div=document.createElement("div");h.html5frag.appendChild(h.html5div)}n=function(){var a=document.body;p=void 0!==a.textContent&&"textContent"||a.innerText&&"innerText"||"innerHTML";n=null;return p};a.extend=function(a){var b,f,d;a=a||{};for(b=1;b<arguments.length;b++)if(d=arguments[b]){for(f in d)d.hasOwnProperty(f)&&(a[f]=d[f]);"function"===typeof d.toString&&d.toString!==Object.prototype.toString&&(a.toString=
d.toString)}return a};a.mixin=function(a){var b,f,d;a=a||{};for(b=1;b<arguments.length;b++)if(d=arguments[b])for(f in d)d.hasOwnProperty(f)&&!a.hasOwnProperty(f)&&(a[f]=d[f]);return a};a.strip=function(a,b){for(var f in a)if(!0===b||a.hasOwnProperty(f))a[f]=null};a.delve=function(a,b,f,d){var j=0;b=b.split(".");for(!0===f&&b.splice(0,1);j<b.length&&a&&a.hasOwnProperty(b[j]);)a=a[b[j]],j+=1;if(j>=b.length||!0===d&&0<j)return a};a.flattenObj=function(c,b,f,d){var j,y;b=b||"";f=f||0;d=d||{};for(j in c)c.hasOwnProperty(j)&&
(y=b?b+"_"+j:j,a.isScalar(c[j])?d[y]=c[j]:a.flattenObj(c[j],y,f+1,d));if(!f)return d};a.template=function(c,b,f){var d;!1!==f&&a.i18n&&(d=a.i18n);return(c+"").replace(h.regex.templateFieldToken,function(f,y,c,h){"\\"!==y&&c?(f=a.delve(b,c))?(d&&(f=d(f)||f),h&&"|"===h.substring(0,1)&&(f=a.text.filter(f,h.substring(1))),f=y+f):f=y:f=y;return f})};a.inherits=function(a,b){function f(){}f.prototype=b.prototype;var d=a.prototype;a.prototype=new f;puredom.extend(a.prototype,d);a.prototype.constructor=a;
a.prototype.__super=b};a.typeOf=function(c){if(void 0===c)return"undefined";if(null===c)return"null";if(c){if(c.constructor===m)return"object";if(a.isArray(c))return"array"}return Object.prototype.toString.call(c).replace(h.regex.parseObjectNameFromString,"$1").toLowerCase()};a.isScalar=function(c){c=a.typeOf(c);return"undefined"===c||"null"===c||"number"===c||"string"===c||"boolean"===c?!0:!1};if(!Array.prototype.indexOf||0!==[a].indexOf(a))try{Array.prototype.indexOf=function(a){for(var b=0;b<this.length;b++)if(this[b]===
a)return b;return-1}}catch(v){}a.toArray=function(a){var b=[],f=a&&a.length;if(f||0===f)for(;f--;)b[f]=a[f];else for(f=0;;){if(a.hasOwnProperty&&a.hasOwnProperty(f))b.push(a[f]);else if(a.hasOwnProperty&&a.hasOwnProperty(f+""))b.push(a[f+""]);else break;f+=1}return b};a.isArray=Array.isArray?function(a){return Array.isArray(a)}:function(a){return"[object Array]"===Object.prototype.toString.call(a)};a.hasOwnProperty=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};a.forEach=function(c,
b){var f,d;if(a.isArray(c))for(f=0;f<c.length&&!(d=b(c[f],f),!1===d);f++);else for(f in c)if(c.hasOwnProperty(f)&&(d=b(c[f],f),!1===d))break;return c};a.foreach=a.forEach;a.setInnerHTML=function(a,b){var f,d;if(h.support.html5)a.innerHTML=b||"";else{a.innerHTML="";h.html5div.innerHTML=b||"";f=document.createDocumentFragment();for(d=h.html5div.childNodes.length;d--;)f.appendChild(h.html5div.firstChild);a.appendChild(f)}};a.createElement=function(c,b){var f,d,j,y;c=c||{};f=document.createElement(c.type||
"div");b=b||c.parent;c.insertBefore&&c.insertBefore.constructor===a.NodeSelection&&(c.insertBefore=c.insertBefore._nodes[0]);!b&&c.insertBefore&&(b=c.insertBefore.parentNode);for(d in c)if(a.hasOwnProperty(c,d))if("on"===(d+"").substring(0,2).toLowerCase())a.addEvent(f,d.substring(2),c[d]);else if("css"===d||"cssText"===d)g&&(c[d]=c[d].replace(h.regex.css3AutoPrefix,"$1"+g+"-$2:$3; $2:$3;"),c[d]=c[d].replace(h.regex.css3VendorPrefix,"-"+g+"-")),f.style.cssText=c[d];else if("html"===d||"innerHTML"===
d)a.setInnerHTML(f,c[d]);else if("attributes"===d)for(j in c[d])a.hasOwnProperty(c[d],j)&&f.setAttribute(j,c[d][j]);else if("parent"!==d&&"children"!==d&&"insertBefore"!==d&&"type"!==d&&"children"!==d&&"html"!==d&&"innerHTML"!==d)if(document.all)try{f[d]=c[d]}catch(e){a.log(d)}else f[d]=c[d];if(b){if(c.insertBefore)try{b.insertBefore(f,c.insertBefore),y=!0}catch(l){y=!1}y||b.appendChild(f)}if(c.children&&a.isArray(c.children)){j=document.createDocumentFragment();for(d=0;d<c.children.length;d++)a.createElement(c.children[d],
j);f.appendChild(j)}return f};a.NodeSelection=function b(f){var d;this._results=[];this._nodes=[];this._animations=[];if(f)if(a.isArray(f))for(d=0;d<f.length;d++)f[d]&&(f[d].constructor===b&&f[d]._nodes?this._nodes.push(f[d]._nodes[0]):this._nodes.push(f[d]));else this._nodes.push(f)};a.extend(a.NodeSelection.prototype,{_results:[],_nodes:[],_animations:[],describe:function(){var b=[];this.each(function(a){var d="<"+a.nodeName(),j=a.prop("id"),c=a.prop("className");j&&(d+=' id="'+j+'"');c&&(d+=' class="'+
c+'"');d+=">";d=1===a._nodes[0].childNodes.length&&3===a._nodes[0].childNodes[0].nodeType?d+a.text().replace(/(\r|\n)/gim,decodeURIComponent("%E2%86%A9")).replace(/\t/gim,decodeURIComponent("%E2%86%92")):d+("["+a.children().count()+" children]");d+="</"+a.nodeName()+">";b.push(d)});return b},toString:function(){return this.describe().join(", ")},toSource:function(){return this._nodes},getResult:function(b){b=Math.round(b)||0;return this._results[this._results.length-b-1]},pushResult:function(b){this._results.push(b);
return this},each:function(b){return this._each(b,!0)},_each:function(b,f,d){var j=this._nodes.slice(0,this._nodes.length),c,h,e;for(c=0;c<j.length&&!(h=c,!0===d&&(h=j.length-h-1),e=j[h],!0===f&&(e=new a.NodeSelection(e)),h=b.call(this,e,h),!1===h);c++);return this},wait:function(b,a){var d=this;a&&setTimeout(function(){a.apply(d);d=a=null},Math.abs(b));return this},nodeName:function(){var b=this._nodes[0],a=b&&b.nodeName&&b.nodeName.toLowerCase();return b===window?"#window":a?a:null},uuid:function(){return this._nodes[0]&&
h.nodeToId(this._nodes[0])||null},text:function(b){if(0===arguments.length)return this._nodes[0]&&this._nodes[0][p||n()]||"";b+="";this._each(function(a){a[p||n()]=b});return this},html:function(b,f){if(0===arguments.length)return this._nodes[0]&&this._nodes[0].innerHTML||"";b+="";h.regex.autoDetectHTMLContent.lastIndex=0;h.regex.autoDetectHTMLContent.test(b)&&!0!==f?this._each(function(d){a.setInnerHTML(d,b)}):this._each(function(a){a[p||n()]=b});return this},css:function(b,f){var d,j=this;f=f||
{};d=a.typeOf(f.tween);if("string"===d&&"none"!==f.tween||"number"===d&&0<f.tween){d=(f.tween+"").replace(h.regex.whitespaceCharacters,"").split(",");var c,e,l=0,g=0;e=function(b){g+=1;g>=l&&(e=null,f.callback&&f.callback(b),j=null)};for(c in b)b.hasOwnProperty(c)&&(l+=1,this.animateCss(c,b[c],d[0],d[1],e))}else this._each(function(d){a.applyCss(d,b)}),f.callback?setTimeout(function(){f.callback(j);j=null},1):j=null;return this},show:function(){this.css({display:"",visibility:"visible"});this._each(function(b){if("none"===
b.style.display||"none"===a.nodeStyle(b,"display"))b.style.display="block"});return this},hide:function(b){return this.css(!1===b?{visibility:"hidden"}:{display:"none"})},fadeIn:function(b,f){var d=parseFloat(this.getStyle("opacity")||"0")||0,j=1;if("none"===this.getStyle("display")||"hidden"===this.getStyle("visibility"))this.getStyle("opacity")&&(0<d&&1>d)&&(j=d),d=0,this.css({opacity:0});"function"===a.typeOf(b)&&(b=f=b);if(1<=d||0==b||!1===b)return this.css({opacity:j}).show(),setTimeout(f,0),
this;this.css({opacity:j},{tween:b||"medium",callback:function(a){f&&f(a);b=f=null}}).show();return this},fadeOut:function(b,f,d){var j=parseFloat(this.getStyle("opacity")||"1")||1;"function"===a.typeOf(b)&&(b=f=b);"boolean"===a.typeOf(f)&&(d=f,f=null,"function"===a.typeOf(d)&&(f=d));if(0>=j||"none"===this.getStyle("display")||"hidden"===this.getStyle("visibility")||0===b||!1===b)return this.css({opacity:0}).hide(d),setTimeout(f,0),this;this.css({opacity:0},{tween:b||"medium",callback:function(a){a.hide(d).css({opacity:j});
f&&f(a);b=f=null}});return this},animateCSS:function(){var b,f,d,j;b=function(b,d,f,j,c){var e=[],l=[],g,q,k;b=b.toLowerCase();"auto"!==d?(g=parseFloat((d+"").replace(h.regex.getNumericCSSValue,""))||0,q=(k="string"===a.typeOf(d)&&d.match(h.regex.getCSSValueUnits))&&k[0]||"px","opacity"===b&&(q="")):q="opacity"===b?"":"px";this._each(function(f,j){var c,k;c={};var t;e[j]=parseFloat((a.nodeStyle(f,b)+"").replace(h.regex.getNonIntegerCharsSigned,""))||0;if("auto"===d||""===d){t=f.style.visibility||
"";c[b]=d;c.visibility="hidden";a.applyCss(f,c);c=a.nodeStyle(f,b);if(c===d||c.indexOf("px")<c.length-3)c=b.substring(0,1).toUpperCase()+b.substring(1).toLowerCase(),c=f["offset"+c]+"px";k="string"===a.typeOf(c)&&c.match(h.regex.getCSSValueUnits);l[j]={_actualTarget:d,numericTargetValue:parseFloat((c+"").replace(h.regex.getNumericCSSValue,""))||0,units:"opacity"===b?"":k&&k[0]||"px"};setTimeout(function(){f.style.visibility=t;f=null},51);c=c=k=null}else l[j]={numericTargetValue:g,units:q}});return this.animate(function(d){this._each(function(f,
j){var c={},h=d*(l[j].numericTargetValue-e[j])+e[j],g=l[j].units;"px"===g?h=Math.round(h):(h=parseFloat(h),h=0===h%1?Math.round(h):h.toFixed(2));c[b]=h+g;a.applyCss(f,c)})},f,j,function(d){d._each(function(d,f){var j={};l[f]._actualTarget&&(j[b]=l[f]._actualTarget,a.applyCss(d,j))});c.apply(d,arguments)})};f=function(b,d,f,j,c){var e=this._createAnimationObj(function(){},f,j,c),l=this,g={},q={};b=(b+"").replace(h.regex.getUpperCaseAlphaChars,"-$1").toLowerCase();"number"===a.typeOf(d)&&"opacity"!==
(b+"").toLowerCase()&&(d+="px");g[b]={duration:e.duration,timingFunction:e.easing};q[b]=d;setTimeout(function(){l._each(function(b){a.updateCssTransitions(b,g);a.applyCss(b,q);h.incrementAnimationCount(b)});e._cb=function(){if(e){var d={};d[b]=null;l._each(function(b){a.updateCssTransitions(b,d);h.decrementAnimationCount(b)});e.callback&&e.callback(l);for(var f in e)if(e.hasOwnProperty(f))try{delete e[f]}catch(j){}}e=q=c=l=null};setTimeout(e._cb,(parseInt(e.duration,10)||0)+20)},10)};j=function(){return d=
void 0!==document.body.style[k+"Transition"]||void 0!==document.body.style.transition};return function(c){"boolean"!==a.typeOf(d)&&j();!1!==a.allowCssTransitions&&d?f.apply(this,arguments):b.apply(this,arguments);return this}}(),animate:function(b,f,d,j){if(b){var c=this,e=this._createAnimationObj.apply(this,arguments),l;this._each(function(b){h.incrementAnimationCount(b)});l=function(b){e.frameTime=b;e.position=e.frameTime-e.start;e.fraction=e.position/e.duration;e.position>=e.duration?(e.fraction=
1,e.position=e.duration):e.easingMethod&&(e.fraction=e.easingMethod.call(a.easingMethods,e.fraction,e));e.animator.call(c,e.fraction,e);if(1===e.fraction){for(b=c._animations.length;b--;)if(c._animations[b]===e){c._animations.splice(b,1);break}e.callback&&setTimeout(function(){c._each(function(b){h.decrementAnimationCount(b)});e.callback.call(c,c,e);c=e=null},10)}else e.timer=a.animationFrame.getTimer(l,a.baseAnimationInterval||10)};a.animationFrame.getTimer(l,a.baseAnimationInterval||10);this._animations.push(e)}return this},
_createAnimationObj:function(b,f,d,j){b={animator:b,duration:f,easing:"string"===a.typeOf(d)?d:"ease",callback:j,start:a.animationFrame.getStartTime(),frameTime:null};if("string"===a.typeOf(b.duration))switch(b.duration.toLowerCase()){case "long":case "slow":b.duration=h.animationTimes.slow;break;case "short":case "fast":b.duration=h.animationTimes.fast;break;default:b.duration=parseInt(b.duration)||h.animationTimes.medium}else b.duration=Math.round(b.duration)||h.animationTimes.medium;h.animationTimeScale&&
(b.duration*=h.animationTimeScale);b.easing&&a.easingMethods.hasOwnProperty(b.easing)?b.easingMethod=a.easingMethods[b.easing]:b.easing=null;return b},classify:function(b){var f=[],d="{*^de^*}"===arguments[0]?"removeClass":"addClass",j,c;for(j=0;j<arguments.length;j++)if(a.isArray(arguments[j]))for(c=0;c<arguments[j].length;c++)f.push(arguments[j][c]);else f.push(arguments[j]);this._each(function(b){a[d](b,f)});return this},declassify:function(b){var a=["{*^de^*}"].concat(Array.prototype.slice.call(arguments,
0));return this.classify.apply(this,a)},hasClass:function(b,a){var d=!0!==a;this._each(function(j){j=-1<(" "+j.className+" ").indexOf(" "+b+" ");!0===a?j&&(d=!0):j||(d=!1)});return d},setOpacity:function(b){this._each(function(f){a.setOpacity(f,b)});return this},sumOf:function(b){var f=0,d=Array.prototype.slice.call(arguments,1);this.constructor.prototype.hasOwnProperty(b)&&this._each(function(j){j=new a.NodeSelection(j);f+=j[b].apply(j,d)});return f},height:function(b,f){var d,j=0;"object"===a.typeOf(b)&&
!f&&(f=b,b=null);f=f||{};if(b||0===b)return b+="","auto"===b?d="":(d=/^([\-0-9\.]+)(.*?)$/.exec(b),b=Math.round(d&&d[1]||b)||0,d=d&&d[2]||"px"),this.css({height:b+d}),this;this._each(function(b){j+=parseInt(b.offsetHeight,10)||0;!0!==f.border&&(j-=parseInt((a.nodeStyle(b,"border-top-width")+"").replace(h.regex.getNonIntegerCharsSigned,""),10)||0,j-=parseInt((a.nodeStyle(b,"border-bottom-width")+"").replace(h.regex.getNonIntegerCharsSigned,""),10)||0);!0===f.margin&&(j+=parseInt((a.nodeStyle(b,"margin-top")+
"").replace(h.regex.getNonIntegerCharsSigned,""),10)||0,j+=parseInt((a.nodeStyle(b,"margin-bottom")+"").replace(h.regex.getNonIntegerCharsSigned,""),10)||0);!1===f.padding&&(j-=parseInt((a.nodeStyle(b,"padding-top")+"").replace(h.regex.getNonIntegerCharsSigned,""),10)||0,j-=parseInt((a.nodeStyle(b,"padding-bottom")+"").replace(h.regex.getNonIntegerCharsSigned,""),10)||0)});return j},width:function(b,f){var d,j=0;"object"===a.typeOf(b)&&!f&&(f=b,b=null);f=f||{};if(b||0===b)return b+="","auto"===b?
d="":(b=(d=/^([\-0-9\.]+)(.*?)$/.exec(b))&&d[1]||b,d=d&&d[2]||"px"),this.css({width:b+d}),this;this._each(function(b){j+=parseInt(b.offsetWidth,10)||0;!0!==f.border&&(j-=parseInt((a.nodeStyle(b,"border-left-width")+"").replace(h.regex.getNonIntegerCharsSigned,""),10)||0,j-=parseInt((a.nodeStyle(b,"border-right-width")+"").replace(h.regex.getNonIntegerCharsSigned,""),10)||0);!0===f.margin&&(j+=parseInt((a.nodeStyle(b,"margin-left")+"").replace(h.regex.getNonIntegerCharsSigned,""),10)||0,j+=parseInt((a.nodeStyle(b,
"margin-right")+"").replace(h.regex.getNonIntegerCharsSigned,""),10)||0);!1===f.padding&&(j-=parseInt((a.nodeStyle(b,"padding-left")+"").replace(h.regex.getNonIntegerCharsSigned,""),10)||0,j-=parseInt((a.nodeStyle(b,"padding-right")+"").replace(h.regex.getNonIntegerCharsSigned,""),10)||0)});return j},x:function(b){var a=this._nodes[0],d=null;if(a&&(d=a.offsetLeft,!0===b))for(;(a=a.parentNode)&&a!==document;)d+=parseFloat(a.offsetLeft)||0;return d},y:function(b){var a=this._nodes[0],d=null;if(a&&(d=
a.offsetTop,!0===b))for(;(a=a.parentNode)&&a!==document;)d+=parseFloat(a.offsetTop)||0;return d},position:function(b,a,d,j){var c;j=j||"px";if(1>arguments.length||1===arguments.length&&!0===arguments[0])return{x:this.x(!0===arguments[0]),y:this.y(!0===arguments[0])};c={};"number"===puredom.typeOf(b)?c.left=b+j:"string"===puredom.typeOf(b)&&(c.left=b);"number"===puredom.typeOf(a)?c.top=a+j:"string"===puredom.typeOf(a)&&(c.top=a);this.css(c,d);return this},scrollLeft:function(b){if(b||0===b)"number"!==
a.typeOf(b)&&(b=Math.round((b+"").replace(h.regex.getNonIntegerCharsSigned,""))),this._each(function(a){a.scrollLeft=b});else return this._nodes&&this._nodes[0]&&this._nodes[0].scrollLeft||0},scrollTop:function(b){if(b||0===b)"number"!==a.typeOf(b)&&(b=Math.round((b+"").replace(h.regex.getNonIntegerCharsSigned,""))),this._each(function(a){a.scrollTop=b});else return this._nodes&&this._nodes[0]&&this._nodes[0].scrollTop||0},focus:function(){this._each(function(b){b.focus&&b.focus()});return this},
blur:function(){this._each(function(b){b.blur&&b.blur()});return this},selectAll:function(){this._each(function(b){b.SelectAll&&b.SelectAll();b.select&&b.select();b.selectionStart&&b.hasOwnProperty("value")&&(b.selectionStart=0,b.selectionEnd=b.value.length)})},getStyle:function(b,f){var d=[];this._each(function(f){d.push(a.nodeStyle(f,b)||null)});return!1===f?(this.pushResult(d),this):1>=d.length?d[0]:d},value:function(b,f){f=f||{};if(null!==b&&void 0!==b&&0<arguments.length)return this._each(function(d){var c=
(d.nodeName+"").toLowerCase(),e=(d.getAttribute("type")||"").toLowerCase();if("input"===c&&("checkbox"===e||"radio"===e))d.checked=!!b;d.value=b;!1!==f.fireChange&&a.fireEvent({type:"change",target:d,value:b})}),this;var d=[];this._each(function(b){var f=(b.nodeName+"").toLowerCase(),c=(b.getAttribute("type")||"").toLowerCase(),e;"input"===f&&("checkbox"===c||"radio"===c)?d.push(!!b.checked):"select"===f?(e=b.multiselect||b.multiSelect?[]:null,a.el(b).query("option")._each(function(b){if(b.selected||
b.checked)a.isArray(e)?e.push(b.value):e=b.value}),d.push(e)):d.push(b.value)});return 2>d.length?d[0]||null:d},attr:function(b,f,d){var j=[],c,e;if(0===arguments.length){j={};for(c=this._nodes[0].attributes.length;c--;)e=this._nodes[0].attributes[c],e.specified&&(j[e.name||e.nodeName]=e.value||e.nodeValue);return j}if(1<arguments.length){if("object"===a.typeOf(b)){for(c in b)"string"===typeof c&&b.hasOwnProperty(c)&&this.attr(j,b[c]);return this}return this._each(function(a){try{a.setAttribute(b,
f),a.removeAttribute&&(null===f||void 0===f)&&a.removeAttribute(b)}catch(d){}})}this._each(function(a){a=a.getAttribute(b);"string"!==typeof a&&(a=null);j.push(a)});return!1===d?(this.pushResult(j),this):1>=j.length?j[0]:j},prop:function(b,a,d){var j=[];if(1<arguments.length)return this._each(function(d){d[b]=a;if(void 0===a)try{delete d[b]}catch(j){}});this._each(function(a){var d;try{d=a[b]}catch(f){console.log("NodeSelection.prop("+b+") :: Access Error",f)}j.push(d||null)});return!1===d?(this.pushResult(j),
this):1>=j.length?j[0]:j},enable:function(){this.attr("disabled",null);this.declassify("_puredom_disabled");return this},disable:function(){this.attr("disabled","disabled");this.classify("_puredom_disabled");return this},enabled:function(b){return!0===b||!1===b?(this[b?"enable":"disable"](),this):"disabled"!==this.attr("disabled")&&!0!==this.prop("disabled")&&!this.hasClass("_puredom_disabled")},addEvent:function(b,f,d){this._each(function(j){a.addEvent(j,b,f,d)});return this},removeEvent:function(b,
f,d){this._each(function(j){a.removeEvent(j,b,f,d)});return this},fireEvent:function(b,f){this._each(function(d){a.fireEvent(a.extend({},f||{},{type:b,target:d}))});return this},_removeAllEvents:function(b){var a;this._each(function(b){h.wrappedEventListener.destroyObjHandlers(b,!0)});a=this.children();!0===b&&0<a.count()&&a._removeAllEvents(!0);a=b=null;return this},appendChild:function(b){if(b&&0<this._nodes.length)if(b.constructor===this.constructor){var a=this._nodes[0];b._each(function(b){a.appendChild(b)})}else this._nodes[0].appendChild(b);
return this},insertBefore:function(b,a){if(b&&0<this._nodes.length){a&&a.constructor===this.constructor&&(a=a._nodes[0]);if(!a||a.parentNode!==this._nodes[0])return this.appendChild(b);if(b.constructor===this.constructor){var d=this._nodes[0];b._each(function(b){d.insertBefore(b,a)},null,!0)}else this._nodes[0].insertBefore(b,a)}return this},insertInto:function(b){var a;b&&0<this.count()&&(b.constructor===this.constructor&&(b=b._nodes[0]),1===this.count()?b.appendChild(this._nodes[0]):(a=document.createDocumentFragment(),
this._each(function(b){a.appendChild(b)},null,!0),!0!==h.support.filters&&b.appendChild(a)));return this},remove:function(){this.fireEvent("remove");this._each(function(b){b.parentNode&&b.parentNode.removeChild(b)});return this},destroy:function(){this.remove();this.fireEvent("destroy");this._removeAllEvents(!0);this._nodes.splice(0,this._nodes.length);return this},query:function(b,f){var d=[];0<this._nodes.length&&this._each(function(j){j=a.getElement(b,puredom.extend({},f||{},{within:j}));a.isArray(j)&&
0<j.length&&(d=d.concat(j))});return new a.NodeSelection(d)},clone:function(b,f){var d=[];!0===f&&(f=this.parent());this._each(function(a){d.push(a.cloneNode(!1!==b))});d=new a.NodeSelection(d);f&&f.appendChild(d);d._each(h.removeNodeUID);!1!==b&&d.query("*")._each(h.removeNodeUID);return d},count:function(){return this._nodes.length},exists:function(){return 0<this.count()},next:function(){for(var b=this._nodes[0]&&this._nodes[0].nextSibling;b&&3===b.nodeType;)b=b.nextSibling;return new a.NodeSelection(b&&
[b]||null)},prev:function(){for(var b=this._nodes[0]&&this._nodes[0].previousSibling;b&&3===b.nodeType;)b=b.previousSibling;return new a.NodeSelection(b&&[b]||null)},previous:function(){return this.prev.apply(this,arguments)},firstChild:function(){return this.children().first()},lastChild:function(){return this.children().last()},nthChild:function(b){return this.children().index(b)},first:function(b){return new a.NodeSelection(this._nodes.slice(0,b||1))},last:function(b){return new a.NodeSelection(this._nodes.slice(this._nodes.length-
(b||1)))},index:function(b,f){return new a.NodeSelection("number"===a.typeOf(b)&&this._nodes.slice(b,b+(f||1))||null)},siblings:function(){var b=new a.NodeSelection;this._each(function(a){for(var d=a;d=d.previousSibling;)"#text"!==d.nodeName&&("#comment"!==d.nodeName&&3!==d.nodeType)&&b._nodes.push(d);for(d=a;d=d.nextSibling;)"#text"!==d.nodeName&&("#comment"!==d.nodeName&&3!==d.nodeType)&&b._nodes.push(d)});return b},parent:function(){var b=[],f;this._each(function(a){(f=a.parentNode)&&(0>b.indexOf(f)&&
11!==f.nodeType)&&b.push(f)});return new a.NodeSelection(b)},children:function(){var b=[],f,d;if(0<this._nodes.length)for(f=0;f<this._nodes.length;f++)if(this._nodes[f].childNodes)for(d=0;d<this._nodes[f].childNodes.length;d++)3!==this._nodes[f].childNodes[d].nodeType&&("#text"!==this._nodes[f].childNodes[d].nodeName&&"#comment"!==this._nodes[f].childNodes[d].nodeName)&&b.push(this._nodes[f].childNodes[d]);return new a.NodeSelection(b)},submit:function(){this._each(function(b){var f=a.fireEvent({type:"submit",
target:b});!1!==f.rval&&!1!==f.returnValue&&!0!==f.preventDefault&&b.submit&&b.submit()})},selection:function(b,f){var d=this._nodes[0],j,c;b&&("number"!==typeof b&&b.start)&&(f=b.end,b=b.start);if("number"===typeof b)0>b&&(b=0),c=d.value.length,f>c&&(f=c),b>f?b=f:f<b&&(f=b),window.getSelection?(d.selectionStart=b,d.selectionEnd=f):d.selectionEnd||0===d.selectionEnd?(d.selectionStart=b,d.selectionEnd=f):d.createTextRange&&(d=d.createTextRange(),d.collapse(!0),d.moveStart("character",b),d.moveEnd("character",
f),d.select());else{if(window.getSelection)return j="string"===typeof d.value?d.value:d.innerHTML,c=window.getSelection(),{start:d.selectionStart+0,end:d.selectionEnd+0,text:j.substring(c.start,c.end)};if(document.selection)return c=document.selection.createRange(),j=document.body.createTextRange(),j.moveToElementText(d),j.setEndPoint("EndToStart",c),{start:j.text.length,end:j.text.length+c.text.length,text:c.text};a.log("Selection retrieval is not supported in this browser.");return{start:0,end:0,
text:""}}return this},template:function(b){var f;b=b||{};f=function(b){b=b.split("|");var a;b.splice(0,1);for(a=b.length;a--;)"htmlEntities"===b[a]&&b.splice(a,1);return b};this.query("[data-tpl-id]").each(function(d){var j=d.nodeName(),c=d.attr("data-tpl-id"),e=c,h;h=f(c);c=c.split("|")[0];e=puredom.delve(b,c);if(null!==e&&void 0!==e){if("date"===typeof e||e.constructor===Date)e=e.toLocaleString();if(c=d.attr("data-tpl-prop"))d.prop(c,a.text.filter(e,h.join("|")));else switch(j){case "select":case "input":case "textarea":case "meter":case "progress":d.value(e);
break;case "img":case "video":case "audio":case "iframe":h.splice(0,0,"htmlEntities");e=a.text.filter(e,h.join("|"));d.attr("src",e);break;default:h.splice(0,0,"htmlEntities"),e=a.text.filter(e,h.join("|")),d.html(e)}}});b=null;return this}});a.NodeSelection.prototype.on=a.NodeSelection.prototype.addEvent;a.NodeSelection.prototype.animateCss=a.NodeSelection.prototype.animateCSS;h.incrementAnimationCount=function(b){b.setAttribute("data-puredom-animation-count",h.getAnimationCount(b)+1+"");a.addClass(b,
"_puredom_animating")};h.decrementAnimationCount=function(b){var f=Math.max(0,h.getAnimationCount(b));1<f?b.setAttribute("data-puredom-animation-count",f-1+""):(b.setAttribute("data-puredom-animation-count",""),b.removeAttribute&&b.removeAttribute("data-puredom-animation-count"),a.removeClass(b,"_puredom_animating"))};h.getAnimationCount=function(b){return parseInt(b.getAttribute("data-puredom-animation-count"),10)||0};h.unload=function(){h.wrappedEventListener.reset();a.getElement.clearCache();h._nodeToIdList=
{};setTimeout(function(){window.puredom=h=m=n=null},10)};a.el=function(b,f){var d,j;if(b){j=a.typeOf(b);if("array"===j){d=[];for(var c=0;c<b.length;c++)Array.prototype.splice.apply(d,[0,0].concat(a.el(b[c])._nodes))}if(b.constructor===a.NodeSelection)return!0===f&&console.log("query is already a NodeSelection",b.constructor+"",b.constructor.name),b;if("string"===j&&"<"===b.charAt(0)||"object"===j&&!b.nodeName&&b!==window)!0===f&&console.log("query is an HTML fragment",b,j),d=a.createElement.apply(a,
arguments);else if("string"===j)!0===f&&console.log("query is a CSS selector",b,j),d=a.getElement(b,arguments[1]);else if(b.nodeName||b===window)!0===f&&console.log("query is an HTML element",b,j),d=b}return new a.NodeSelection(d)};a.node=function(b){return new a.NodeSelection(h.idToNode(b))};var l,t,q={},A=!1,C=/^((?:[a-z][a-z0-9\_\-]*)|\*)?/gi,x=/^\s*(.*?)\s*$/gm,u;u=[{title:"ID selector {#id}",regex:/^#[_a-zA-Z0-9-]*/gm,filter:function(b,a,d){return[(d.searchBaseNode&&d.searchBaseNode.getElementById?
d.searchBaseNode:document).getElementById(b[0].substring(1))]}},{title:"Class selector {.className}",regex:/^\.([^#.:\[<>\{+\|\s]+)/gim,filter:function(b,a){var d,j,c=" "+b[1]+" ";for(d=a.length;d--;)j=a[d]&&a[d].className,(!j||-1===(" "+j+" ").indexOf(c))&&a.splice(d,1)}},{title:"Attribute selector {[name=value] & variants}",regex:/^\[([^\^\$\~=]+)(?:([\^\$\~=]+)(['"]?)([^\]]*))?\3\]/g,filter:function(b,f){var d,j,c,e,h,l,g,q;if(b&&b[1]){d=b[1];c=j=void 0;b[2]&&b[4]&&(j=b[2],c=b[4]||"");for(l=f.length;l--;){g=
"checked"===d?"true"===c||"false"===c?f[l].checked?"true":"false":f[l].checked?"checked":null:"selected"===d?"true"===c||"false"===c?f[l].selected?"true":"false":f[l].selected?"selected":null:f[l]&&f[l].getAttribute(d+"");e="string"===a.typeOf(g);h=g&&0<g.length;c&&(q=e?g.indexOf(c):-1);switch(j||""){case "=":e=g===c;break;case "^=":e=0===q;break;case "$=":e=h&&g.substring(g.length-c.length)===c;break;case "~=":e=-1<q;break;default:e=!c&&e}e||f.splice(l,1)}}}},{title:"Descendant selector {>}",regex:/^\s*\>\s*((?:[a-z][a-z0-9\:\_\-]*)|\*)?/gi,
filter:function(b,f,d){var c=[].concat(f);b=(b[1]||"*").toLowerCase();var e,h,l;f.splice(0,f.length);!d.isFiltered&&d.first&&a.log("Descendant selector called on an unfiltered result set.  Operating on descendants of the document.");if(!d.isFiltered||d.first)c=[d.searchBaseNode];for(d=0;d<c.length;d++){h=c[d].childNodes;for(e=0;e<h.length;e++)l=(h[e].nodeName+"").toLowerCase(),(l===b||"*"===b&&"#"!==l.charAt(0)&&(1===h[e].nodeType||9===h[e].nodeType))&&f.push(h[e])}}},{title:"nth-child aliases, like :first-child",
regex:/^\:(first|last|only)\-(child|of\-type)/gm,filter:function(b,f,d){var c={"first-child":":nth-child(0n+1)","first-of-type":":nth-of-type(0n+1)","last-child":":nth-last-child(0n+1)","last-of-type":":nth-last-of-type(0n+1)"},e,h;for(e=u.length;e--;)if(!0===u[e].isNthChildSelector){h=u[e];break}if(c.hasOwnProperty(b[1]+"-"+b[2])&&h)return b=c[b[1]+"-"+b[2]],h.regex.lastIndex=0,b=h.regex.exec(b),h.filter(b,f,d);a.log('Unknown nth-child alias "'+b[1]+"-"+b[2]+'"')}},{isNthChildSelector:!0,title:"nth-child selector {:nth-child(n+2) & variants}",
regex:/^\:(nth(?:\-last)?(?:\-of\-type|\-child))\((?:(\-?[0-9]*n(?:[+-][0-9]+)?)|([0-9]+)|([a-z]+))\)/gm,filter:function(b,f){var d,c,e,h,l,g,q,k,t,m=-1!==b[1].indexOf("-of-type");e={odd:[2,1],even:[2]};d=f.splice(0,f.length);-1!==b[1].indexOf("-last")&&d.reverse();b[2]?(c=b[2].split("n"),0===c[0].replace("-","").length&&(c[0]+="1"),k=Math.round(c[0].replace("+",""))||0,t=Math.round(c[1].replace("+",""))||0):b[3]?(k=0,t=Math.round(b[3])||0):b[4]&&(c=b[4].toLowerCase(),e.hasOwnProperty(c)?(k=e[c][0]||
0,t=e[c][1]||0):a.log('Unknown named nth-child expression "'+r[4]+'"'));if(!(0>=k+t)){k===t&&(t=0);for(c=0;c<d.length;c++){children=(d[c].parentNode||{}).childNodes;l=(d[c].nodeName+"").toLowerCase();isMatch=!1;if(children)for(e=q=0;e<children.length;e++)if(g=children[e],h=m?(g.nodeName+"").toLowerCase()===l:"#"!==(g.nodeName+"").substring(0,1)||1===g.nodeType||9===g.nodeType)if(q+=1,g===d[c]&&(isMatch=0<k?0===q%k-t:q===t))break;isMatch&&f.push(d[c])}}}},{title:"within_internal selector { }",regex:/^\s+((?:[a-z][a-z0-9\:\_\-]*)|\*)?/gi,
filter:function(b,f){var d=[].concat(f),c=b[1]||"*",e;f.splice(0,f.length);for(e=0;e<d.length;e++)Array.prototype.splice.apply(f,[f.length-1,0].concat(a.toArray(d[e].getElementsByTagName(c))))}}];t=function(b){b.lastIndex=0};l=function(b,f){var d=document&&document.documentElement||document,c,e,g=b,k,m,n,p,s=0,v=!1;p=!h.support.querySelectorAll;var w=Date.now();b=(b+"").replace(x,"$1");f=puredom.extend({},f||{});!0===f.logging&&(v=!0);if(A&&!0===f.useCache&&q[b])return q[b];f.within&&(d=f.within);
d&&(d.length&&!d.nodeName&&d.indexOf&&d[0])&&(d=d[0]);if(-1<b.indexOf(",")){b=b.split(",");c=[];for(n=b.length;n--;)if(b[n]=b[n].replace(x,"$1"),0<b[n].length&&(d=l(b[n],puredom.extend({},f,{logging:!1,internalLogging:v,internal:!0}))))for(e=0;e<d.length;e++)-1===c.indexOf(d[e])&&c.push(d[e]);v&&a.log("query=",g,", result=",node);w=Date.now()-w;100<w&&a.log('Slow Selector Warning: "'+g+'" took '+w+"ms to complete.");return c}e=b.match(C);e=(e&&e[0]||"").toLowerCase();n=b=b.substring(e.length);">"===
g.charAt(0)&&(p=!0);if(n.match(/^#[^\s\[\]\(\)\:\*\.\,<>#]+$/gim))c=[(d.getElementById?d:document).getElementById(n.substring(1))],p=!1;else if(h.support.querySelectorAll&&!0!==p){k=g.replace(/(\[[^\[\]= ]+=)([^\[\]"']+)(\])/gim,'$1"$2"$3');try{c=a.toArray(d.querySelectorAll(k)||[])}catch(z){console.log("Native querySelectorAll failed for selector: ",k,", error:",z.message),c=[],p=!0}}if(p){"#"===b.substring(0,1)?c=[]:(!e||"*"===e)&&document.all&&!window.opera&&(d===document||d===document.documentElement)?
(c=a.toArray(d.all||document.all),m=!1):(c=a.toArray(d.getElementsByTagName(e||"*")),m=!0);for(k={searchBaseNode:d,negated:!1,first:!0,isFiltered:m||!!(e&&"*"!==e)};0<n.length;){s+=1;p=!1;for(e=0;e<u.length;e++){t(u[e].regex);if(d=u[e].regex.exec(n))p=!0,v&&a.log((u[e].title||u[e].regex)+' ==>> matched:"'+n.substring(0,d[0].length)+'" ==>> remaining:"'+n.substring(d[0].length)+'" ||debug>> (submatches:'+d.slice(1).join(",")+")"),(m=u[e].filter(d,c,k))&&a.isArray(m)&&(c=m),n=n.substring(d[0].length),
k.first=!1,k.isFiltered=!0;if(0===n.length)break}if(!p)throw Error("puredom.getElement() :: Unknown CSS selector near: "+n.substring(0,20),"puredom.js",1775);}}if(!0!==f.includeInvisibles)for(e=c.length;e--;)c[e]&&"#"===(c[e].nodeName+"").charAt(0)&&c.splice(e,1);v&&a.log("query=",g,", result=",c);A&&!0===f.cache&&(q[b]=c);!0!==f.internal&&!0===v&&(w=Date.now()-w,10<w&&a.log('Slow Selector Warning: "'+g+'" took '+w+"ms to complete. "+s+" parse iterations."));return c};l.enableCache=function(b){(A=
!1!==b)||(q={})};l.disableCache=function(){A=!1;q={}};l.clearCache=function(){q={}};l._normalizeSelectorFilter=function(b){2===arguments.length&&(b={regex:arguments[0],filter:arguments[1]});return b&&b.regex&&b.filter?b:!1};l.addSelectorFilter=function(b){return(b=l._normalizeSelectorFilter.apply(l,arguments))?(u.push(b),!0):!1};l.removeSelectorFilter=function(b){var a,d,c;if(b=l._normalizeSelectorFilter.apply(l,arguments))for(a=u.length;a--;){c=!0;for(d in u[a])if(u[a].hasOwnProperty(d)&&u[a][d]!==
b[d]){c=!1;break}if(c){u.splice(a,1);break}}return!0===c};l.selectorStats=function(){return"disabled"};a.getElement=l;a.selectorEngine=a.getElement;a.DOMEvent=function(){};h.wrappedEventListener={list:[],none:{},summary:function(){for(var b=0;b<this.list.length;b++)a.log(h.idToNode(this.list[b].target),".on",this.list[b].type," -> ",this.list[b].handler.displayName||this.list[b].handler.name)},reset:function(b){var f;if(!0===b)for(b=this.list.length;b--;)f=this.list[b],this.list[b]=this.none,a.removeEvent(h.idToNode(f.target),
f.type,f.wrappedHandler),this.unsetRefs(f),window.killCount=(window.killCount||0)+1;this.list.splice(0,this.list.length)},destroyObjHandlers:function(b){var f,d,c=h.nodeToId(b);for(f=this.list.length;f--;)d=this.list[f],d.target===c&&(this.unsetRefs(d),this.list.splice(f,1),a.removeEvent(b,d.type,d.wrappedHandler),window.killCount=(window.killCount||0)+1)},get:function(b,a,d,c){var e,l;d=h.nodeToId(d);for(e=this.list.length;e--;)if(l=this.list[e],l.target===d&&l.handler===a&&l.type===b){a=l.wrappedHandler;
!0===c&&(this.list.splice(e,1),window.killCount=(window.killCount||0)+1,this.unsetRefs(l));break}return a},unsetRefs:function(b){b.wrappedHandler.type=null;b.wrappedHandler.handler=null;b.wrappedHandler.target=null},internalFireEvent:function(b){var a=h.nodeToId(b.target),d=b.type.replace(/^on/gm,""),c,e;for(c=this.list.length;c--&&!(e=this.list[c],e.target===a&&e.type===d&&(e=e.handler.call(b.target,b),!1===e)););},create:function(b,c,d){d={type:b,target:h.nodeToId(d),handler:c,wrappedHandler:function(b){var d=
arguments.callee.handler,c=(arguments.callee.type||b.type).toLowerCase().replace(/^on/,""),f=this!==window?this:h&&h.idToNode(arguments.callee.target),e,l,g={isInSelf:!1,doPreventDefault:!1,doCancelBubble:!1,doStopPropagation:!1,e:b||window.event,ret:null,end:function(){b=e=g=d=c=f=g.end=null;return this.ret}};(!h||!h.idToNode)&&a.log("target:<"+b.target.nodeName+' class="'+b.target.className+'" id="'+b.target.id+'"> , type:'+c+"/"+b.type);b=g.e;e=a.extend(new a.DOMEvent,{which:b.which,type:c,target:b.target||
b.srcElement||f||document.body,relatedTarget:b.relatedTarget||("mouseout"===c?b.toElement:b.fromElement),preventDefault:function(){g.doPreventDefault=!0},stopPropagation:function(){g.doStopPropagation=!0;g.doCancelBubble=!0},cancel:function(){e.preventDefault();e.stopPropagation();return e.returnValue=!1},returnValue:!0,originalEvent:b,timeStamp:b.timeStamp||Date.now()});e.cancelBubble=e.stopPropagation;e.stop=e.prevent=e.cancel;for(l in b)!e.hasOwnProperty(l)&&("function"!==typeof b[l]&&l!==l.toUpperCase())&&
(e[l]=b[l]);e.target||a.log("Event target doesn't exist for type \""+e.type+'": ',e.target,", srcElement=",b.srcElement);if("touchend"===b.type&&h._lastTouchPos)e.pageX=h._lastTouchPos.pageX,e.pageY=h._lastTouchPos.pageY;else if(b.touches&&b.touches[0])e.pageX=b.touches[0].pageX,e.pageY=b.touches[0].pageY,h._lastTouchPos={pageX:e.pageX,pageY:e.pageY};else if(b.pageX||0===b.pageX||b.clientX||0===b.clientX)e.pageX=b.pageX||b.clientX+document.body.offsetLeft,e.pageY=b.pageY||b.clientY+document.body.offsetTop;
if(-1<c.indexOf("key")||b.keyCode||b.charCode)e.keyCode=b.keyCode||b.which,e.charCode=b.keyCode||b.charCode||b.which,e.which=b.which;if(-1<c.indexOf("mouse")||-1<c.indexOf("click")||null!==b.button&&void 0!==b.button)e.button=b.button||b.which;e.target&&(3===e.target.nodeType&&3!==f.nodeType)&&(e.target=e.target.parentNode);g.searchNode=e.relatedTarget||e.target;do if(g.searchNode===f){g.isInSelf=!0;break}while(g.searchNode&&(g.searchNode=g.searchNode.parentNode)&&g.searchNode!==document);if("mouseover"!==
c&&"mouseout"!==c||!g.isInSelf){d&&d.call&&(g.handlerResponse=d.call(f,e));e.returnValue=!1!==g.handlerResponse&&!1!==e.returnValue;g.doPreventDefault&&(e.returnValue=b.returnValue=!1,b.preventDefault&&b.preventDefault());if(g.doCancelBubble||g.doStopPropagation||!0===e.cancelBubble)if(b.stopPropagation&&b.stopPropagation(),b.cancelBubble){if(b.cancelBubble.call)try{b.cancelBubble()}catch(q){}}else try{b.cancelBubble=!0}catch(k){}g.ret=e.returnValue}else g.ret=!0;return g.end()}};d.wrappedHandler.displayName=
"wrappedEventHandler_"+b;d.wrappedHandler.handler=c;d.wrappedHandler.type=b;d.wrappedHandler.target=d.target;this.list.push(d);d=b=c=d=null;return this.list[this.list.length-1].wrappedHandler}};h.getSubjectDescription=function(b){return(b.nodeName?a.el(b)+"":b.constructor&&b.constructor.name||b.name||b)+""};a.eventTypeMap={};h.support.webkitMultitouch&&a.extend(a.eventTypeMap,{mousedown:"touchstart",mousemove:"touchmove",mouseup:"touchend"});a.addEvent=function(b,c,d,e){var g;if(b){"string"===a.typeOf(c)&&
-1<c.indexOf(",")&&(c=c.replace(/\s/gm,"").split(","));if(a.isArray(c)){for(e=0;e<c.length;e++)a.addEvent(b,c[e],d);return!0}g=c=(c+"").toLowerCase().replace(/^\s*(on)?(.*?)\s*$/gim,"$2");"string"!==typeof c||!d||!d.call?a.log("Attempted to add event with invalid type or handler:",{type:c,handler:d+"",subject:h.getSubjectDescription(b),useCapture:!0===e}):(a.eventTypeMap.hasOwnProperty(c)&&(c=a.eventTypeMap[c]),d=h.wrappedEventListener.create(g,d,b),b.attachEvent?b.attachEvent("on"+c,d):b.addEventListener&&
(b.addEventListener(c,d,!0===e),window._eventCount=(window._eventCount||0)+1))}};a.removeEvent=function(b,c,d,e){var g;if(b){"string"===a.typeOf(c)&&-1<c.indexOf(",")&&(c=c.replace(/\s/gm,"").split(","));if(a.isArray(c)){for(g=0;g<c.length;g++)a.removeEvent(b,c[g],d,e);return!0}g=c=(c+"").toLowerCase().replace(/^\s*(on)?(.*?)\s*$/gim,"$2");if("string"!==typeof c||!d||!d.call)a.log("Attempted to remove event with invalid type or handler:",{type:c,handler:d+"",subject:h.getSubjectDescription(b),useCapture:!0===
e});else if(a.eventTypeMap.hasOwnProperty(c)&&(c=a.eventTypeMap[c]),d=h.wrappedEventListener.get(g,d,b,!0),b.detachEvent)b.detachEvent("on"+c,d);else if(b.removeEventListener)try{b.removeEventListener(c,d,!0===e),window._eventCount=(window._eventCount||0)-1}catch(l){}}};a.cancelEvent=function(b){if(b=b||window.event){b.preventDefault&&b.preventDefault();b.stopPropagation&&b.stopPropagation();try{b.cancelBubble=!0}catch(a){}b.returnValue=!1}return!1};a.fireEvent=function(b){var c,d,e,g,l;b=b||{};if(document.createEventObject){b=
a.extend({},b);b.type="on"+b.type.toLowerCase().replace(/^on/,"");try{c=document.createEventObject()}catch(q){l=!0}if(!l){for(e in b)if(b.hasOwnProperty(e))try{c[e]=b[e]}catch(k){}try{d=b.target.fireEvent(b.type,c),g=!0===c.preventDefault}catch(t){l=!0}}l&&h.wrappedEventListener.internalFireEvent&&h.wrappedEventListener.internalFireEvent(b)}else{c=document.createEvent("HTMLEvents");c.initEvent(b.type.toLowerCase().replace(/^on/,""),!0,!0);for(e in b)if(b.hasOwnProperty(e))try{c[e]=b[e]}catch(m){}d=
!b.target.dispatchEvent(c);g=!0===c.preventDefault}return{evt:c,preventDefault:g,rval:d}};h._nodeToIdIndex=0;h._nodeToIdList={};h.nodeToId=function(b){var c;if(b===window)return"_td_autoid_window";if(b===document)return"_td_autoid_document";if(b===document.body)return"_td_autoid_documentbody";(c=/\s_td_autoid_([0-9]+)\s/gm.exec(" "+b.className+" "))&&c[1]?c=c[1]:(h._nodeToIdIndex+=1,c=h._nodeToIdIndex+"",a.addClass(b,"_td_autoid_"+c));h.ensureNodeIdListing(b,c);return c};h.idToNode=function(b){var c;
c=h._nodeToIdList[b+""];var d;if("_td_autoid_window"===b)return window;if("_td_autoid_document"===b)return document;if("_td_autoid_documentbody"===b)return document.body;c&&(d=a.getElement(c),/\s_td_autoid_[0-9]+\s/gm.exec(" "+d.className+" ")||(d=null));d||(d=(c=a.getElement("._td_autoid_"+b))&&c[0])&&h.ensureNodeIdListing(d,b);return d||!1};h.ensureNodeIdListing=function(b,a){var d;b.getAttribute&&(d=b.getAttribute("id"),d||(d="_td_autoid_"+a,b.setAttribute("id",d)),h._nodeToIdList[a]="#"+d)};h.removeNodeUID=
function(b){var a=b.getAttribute("id");a&&a.match(/^_td_autoid_[0-9]+$/g)&&(b.removeAttribute?b.removeAttribute("id"):b.setAttribute("id",""));b.className&&(b.className=b.className.replace(/(^|\b)_td_autoid_[0-9]+(\b|$)/gim,""))};var z=void 0,w={manualFramerate:11};window.mozRequestAnimationFrame?z="moz":window.webkitRequestAnimationFrame&&(z="webkit");w.nativeSupport=!!z;w.nativeSupport?(w.getTimer=function(b){return window[z+"RequestAnimationFrame"](b)},w.cancelTimer=function(b){window[z+"CancelRequestAnimationFrame"](b)},
w.getStartTime=function(){return window[z+"AnimationStartTime"]||(new Date).getTime()}):(w.getTimer=function(b){return setTimeout(function(){b((new Date).getTime());b=null},w.manualFramerate)},w.cancelTimer=function(b){clearTimeout(b)},w.getStartTime=function(){return(new Date).getTime()});a.animationFrame=w;a.setOpacity=function(b,a){1>=a&&0<a&&(a*=100);a=Math.round(a);100>a?(b.style.opacity=parseFloat(a/100).toFixed(2),b.style.filter="alpha(opacity="+a+")"):(b.style.opacity=null,b.style.filter=
null)};a.applyMsFilter=function(b,c,d){var e,g="",l="MsFilter"===h.support.filterProperty?'"':"",q,k,t;c=c.charAt(0).toUpperCase()+c.substring(1);if("string"===typeof d){g=d;d={};k=g.replace(/\s*(,|=)\s*      /gm,"$1").split(",");for(q=0;q<k.length;q++)t=k[q].indexOf("="),d[k[q].substring(0,t)]=k[q].substring(t+1)}else{for(q in d)d.hasOwnProperty(q)&&(g+=", "+q+"="+d[q]);g=g.replace(",","")}try{e=b.filters&&b.filters.item&&(b.filters.item("DXImageTransform.Microsoft."+c)||b.filters.item(c))}catch(m){}if(e){for(q in d)d.hasOwnProperty(q)&&
"enabled"!==q&&(e[q]=d[q]);e.enabled=d.enabled?1:0}else d=b.style.MsFilter||b.style.filter||"",(d+=" "+(a.nodeStyle(b,"MsFilter")||a.nodeStyle(b,"filter")||""))&&(d=d.replace(RegExp('(^|s|))"?((progid:)?DXImageTransform.Microsoft.)?'+c+'s*?(.*?)"?s*?',"gim"),"$1")+" "),b.style[h.support.filterProperty]=d+l+"progid:DXImageTransform.Microsoft."+c+"("+g+")"+l;b.style.zoom||(b.style.zoom=1)};a.applyCss=function(b,c){var d,e,l,q,t;c=c||{};for(d in c)if(c.hasOwnProperty(d))try{if(e=a.getStyleAsCSS(d),e=
e.replace(/^\-(moz|webkit|ms|o|vendor)\-/gim,g+"-"),e=a.getStyleAsProperty(e),"opacity"===e&&h.support.filters)t=Math.round(100*parseFloat(c[d])),100>t?a.applyMsFilter(b,"alpha",{enabled:!0,opacity:t}):a.applyMsFilter(b,"alpha",{enabled:!1});else if("--box-shadow"===e&&h.support.filters)l=(l=c[d].match(/\b(\#[0-9af]{3}[0-9af]{3}?|rgba?\([0-9\,\s]+\))\b/gim))&&l[0]||"",q=(" "+c[d]+" ").replace(l,"").replace(/\s+/m," ").split(" ").slice(1,4),a.applyMsFilter(b,"glow",{Color:l,Strength:Math.round(q[3].replace(/[^0-9\-\.]/gim,
""))});else if(b.style[e]=c[d],"boxShadow"===e||"textShadow"===e||"borderRadius"===e)k&&(b.style[k+e]=c[d])}catch(m){}};a.getStyleAsProperty=function(b){return"string"===a.typeOf(b)&&b.replace(/\-[a-z0-9]/gim,function(b){return b.charAt(1).toUpperCase()})||null};a.getStyleAsCSS=function(b){return"string"===a.typeOf(b)&&b.replace(/\-*[A-Z]/gm,"-$0").toLowerCase()||null};a.getCssTransitions=function(b){var c={},d={properties:"-vendor-transition-property",durations:"-vendor-transition-duration",timingFunctions:"-vendor-transition-timing-function"},
e,g;for(e in d)d.hasOwnProperty(e)&&(d[e]=(a.nodeStyle(b,d[e])||"").replace(/\s/,"").split(","));for(b=0;b<d.properties.length;b++)d.properties[b]&&("null"!==d.properties[b]&&!("all"===d.properties[b]&&d.durations[b].match(/^[0\.ms]*$/)))&&(e=d.durations[b]||d.durations[d.durations.length-1],g=parseFloat(e.replace(/[^\-0-9\.]/gim,""))||0,e.match(/ms$/i)||(g*=1E3),c[a.getStyleAsProperty(d.properties[b])]={duration:g,timingFunction:d.timingFunctions[b]||d.timingFunctions[d.timingFunctions.length-1]||
"ease"});return c};a.setCssTransitions=function(b,c){var d={"-vendor-transition-property":[],"-vendor-transition-duration":[],"-vendor-transition-timing-function":[]},e;for(e in c)c.hasOwnProperty(e)&&c[e]&&(d["-vendor-transition-property"].push(e.toLowerCase()),d["-vendor-transition-duration"].push((c[e].duration/1E3).toFixed(3)+"s"),d["-vendor-transition-timing-function"].push(c[e].timingFunction||"ease"));for(e in d)d.hasOwnProperty(e)&&(d[e]=d[e].join(", "));a.applyCss(b,d)};a.updateCssTransitions=
function(b,c){var d,e;if(c){d=a.getCssTransitions(b);for(e in c)c.hasOwnProperty(e)&&(c[e]?d[e]=c[e]:delete d[e]);a.setCssTransitions(b,d)}};a.addClass=function(b,c){var d,e;if(c){a.isArray(c)||(c=[c]);d=b.className||"";if(0<d.length){d=" "+d+" ";for(e=0;e<c.length;e++)for(;-1<d.indexOf(" "+c[e]+" ");)d=d.replace(" "+c[e]+" "," ");d=d.substring(1)}b.className=(d+c.join(" ")).replace(/\s+/gim," ")}};a.removeClass=function(b,c){var d,e;if(c){a.isArray(c)||(c=[c]);d=b.className||"";if(0<d.length){d=
" "+d+" ";for(e=0;e<c.length;e++)for(;-1<d.indexOf(" "+c[e]+" ");)d=d.replace(" "+c[e]+" "," ");d=d.substring(1)}b.className=d.replace(/\s+/gim," ")}};a.nodeStyle=function(b,a){var c=(a+"").replace(/[A-Z]/g,"-$0").toLowerCase(),e,l,c=c.replace(/^\-(moz|webkit|ms|o|vendor)\-/gim,g+"-");e=c.replace(/\-[a-z]/gim,function(b){return b.substring(1).toUpperCase()});if("opacity"===c&&h.support.filters)return b.filters.alpha&&!1!==b.filters.alpha.enabled&&Math.round(b.filters.alpha.opacity)/100;b.style&&b.style[e]?
l=b.style[e]||"":b.currentStyle&&b.currentStyle[e]?l=b.currentStyle[e]||b.currentStyle[c]||"":document.defaultView&&document.defaultView.getComputedStyle?l=(l=document.defaultView.getComputedStyle(b,null))&&(l.getPropertyValue(c)||l.getPropertyValue(e))||"":window.getComputedStyle&&(l=(l=window.getComputedStyle(b,null))&&(l.getPropertyValue(c)||l.getPropertyValue(e))||"");return l};a.htmlEntities=function(b,c){var d=["htmlEntities"];!0===c&&d.push("stripTags");return a.text.filter(b,d)};a.log=function(){window.console&&
window.console.log&&window.console.log.apply(window.console,arguments)};a.addNodeSelectionPlugin=function(b,c){a.NodeSelection.prototype.hasOwnProperty(b)||(a.NodeSelection.prototype[b]=function(){var b=c.apply(this,arguments);if(null===b||void 0===b)return this})};a.init=function(){c||(c=!0,a.forEach(h.oninit,function(b){b.call(a,a)}),a.fireEvent({target:document.body,type:"puredomready",puredom:a}))};a.addEvent(document,"DOMContentLoaded",a.init);a.addEvent(window,"load",a.init);a.addEvent(window,
"unload",h.unload);if(window._previousPureDom){for(var B in window._previousPureDom)window._previousPureDom.hasOwnProperty(B)&&(a[B]=window._previousPureDom[B]);window._previousPureDom=null;try{delete window._previousPureDom}catch(D){}}h.puredom=function(b){return"function"===a.typeOf(b)?(!0===c?b.call(a,a):h.oninit.push(b),a):a.el.apply(a,arguments)};a.extend(a,e);a.toString=function(){return"function puredom(){}"};window.puredom=a})();window.puredom=window.puredom||{};
(function(){var a,e=function(){return e.filter.apply(this,arguments)},c=/[&<>"]/gim,g=/(^|\s)[a-z]/gim,k=/^[a-z]/gim,m=/\r?\n/g,p=/[^0-9.\-]/gim;e.filter=function(a,c){var g,h,k,m,n;"array"!==puredom.typeOf(c)&&(c=((c||"")+"").split("|"));if(2<arguments.length)for(g=2;g<arguments.length;g++)"array"===puredom.typeOf(arguments[g])?c=c.concat(arguments[g]):c.push(arguments[g]);for(g=0;g<c.length;g++)for(n in h=c[g],m=[a],k=h.indexOf(":"),-1<k&&(h=h.substring(0,k),m=m.concat(c[g].substring(k+1).split(","))),
e)if((n+"").toLowerCase()===h.toLowerCase()){a=e[n].apply(e,m);break}return a};e.escape=function(a){return encodeURIComponent(a)};e.unescape=function(a){return decodeURIComponent(a)};e.htmlEntities=function(a){var e={"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"};return(a+"").replace(c,function(a){return e[a]})};e.ucWords=function(a){return(a+"").toLowerCase().replace(g,function(a){return a.toUpperCase()})};e.ucFirst=function(a){return(a+"").toLowerCase().replace(k,function(a){return a.toUpperCase()})};
e.nl2br=function(a){return(a+"").replace(m,"<br />")};e.numbersOnly=function(a){return(a+"").replace(p,"")};e.truncate=function(a,c,e,g){var h=!1,k=a+"";a=k;c=parseInt(c,10)||80;g=g||"...";a.length>c&&(!0===e||"true"===e||"byWord"===e?(a=a.substring(0,c),k.charAt(c).match(/\s/)||(a=a.replace(/\s[^\s]*$/,""))):a=a.substring(0,c-g.length),h=!0);h&&(a+=g);return a};e.trim=function(a){var c=/\s/,e;a=a.replace(/^\s\s*/,"");for(e=a.length;c.test(a.charAt(--e)););return a.slice(0,e+1)};e["default"]=function(a,
c){return(a=e.trim(a))?a:c};e.dateformat=function(a,c){var e=puredom.i18n,g=puredom.date,h;g&&g.create&&(h=g.create(a));if(!h||-1<(h+"").indexOf("Invalid"))if(h=new Date(a),!h||-1<(h+"").indexOf("Invalid"))h=new Date,h.setTime(Math.round(a));c&&-1<c.indexOf("%")?g&&g.format&&(a=g.format(h,c)):e&&(a=e(h,null,null,{datetype:c||"date"})||h+"");return a};a=e;var n={},h=function(){if(this.constructor!==arguments.callee&&this.constructor!==h)return new h;this.data={}};puredom.extend(h.prototype,{defaultType:"_default",
purge:function(){this.data={}},get:function(a,c,e){var g;2===arguments.length&&(e=c=a,a=null);a=(a||this.defaultType)+"";c+="";g=this.data.hasOwnProperty(a)&&this.data[a][c]||!1;return e?(g&&e(g),!!g):g},set:function(a,c,e){2===arguments.length&&(e=c=a,a=null);a=(a||this.defaultType)+"";this.data[a]||(this.data[a]={});this.data[a][c+""]=e},proxySet:function(a,c,e,g){var h=this;return function(){h.set(a,c,arguments[g||0]);e&&e.apply(e,arguments)}},each:function(a){return puredom.foreach(this.data,
a)}});var s=function(a){return"string"===puredom.typeOf(a)?s.parse(a):s.stringify(a)};s.stringify=function(a){var c;try{c=JSON.stringify(a)}catch(e){puredom.log("puredom.json:: Stringify failed: "+e+" | "+a)}return c};s.parse=function(a){var c;if("string"===typeof a&&0<a.length)try{c=JSON.parse(a)}catch(e){puredom.log("puredom.json:: Parse failed: "+e+" | "+a)}return c};s.serialize=s.stringify;s.unserialize=s.parse;a={text:a,parameterize:function(a,c){var e=[],g,h,k,m=puredom.extend({delimiter:"&",
startDelimiter:"?",assignment:"=",typeHandlers:null},c);for(g in a)if(a.hasOwnProperty(g))if(h=a[g],k=this.typeOf(h),m.typeHandlers&&m.typeHandlers.hasOwnProperty(k))e.push(m.delimiter+encodeURIComponent(g)+"="+encodeURIComponent(m.typeHandlers[k](h)));else if("array"===k&&!0!==m.disableArrayParams)for(k=0;k<h.length;k++)e.push(m.delimiter+encodeURIComponent(g)+"[]="+encodeURIComponent(h[k]));else{switch(k){case "boolean":h=h?"true":"false";break;case "null":case "undefined":h="";break;case "object":h=
!1!==m.useJsonForObjects?this.json(h):this.parameterize(h)}e.push(encodeURIComponent(g)+"="+encodeURIComponent(h))}e=e.join(m.delimiter||"&");return e=(m.startDelimiter||"")+e},querystring:{parse:function(a){var c,e,g={};"?"===a.substring(0,1)&&(a=a.substring(1));a=a.split("&");for(c=0;c<a.length;c++)a[c]&&(e=a[c].indexOf("="),g[decodeURIComponent(a[c].substring(0,e))]=0>e?"":decodeURIComponent(a[c].substring(e+1)));return g},stringify:function(a,c){c=puredom.extend({startDelimiter:""},c||{});return puredom.parameterize(a,
c)},build:function(){return puredom.querystring.stringify.apply(puredom.querystring,arguments)}},cookies:{set:function(a,c,e,g,h,k){var m="",p="",s;h="string"===typeof h?h:"";e&&(s=new Date,s.setTime(s.getTime()+864E5*e),m="; expires="+s.toGMTString());n.hasOwnProperty(a)&&n[a].expires&&(m="; expires="+n[a].expires.toGMTString());p=a+"="+encodeURIComponent(c)+m+"; path=/"+h.replace(/^\//,"");"string"===typeof g&&0<g.length&&(p+="; domain="+g.replace(/[\;\,]/,""));!0===k&&(p+="; secure");document.cookie=
p;n[a]={value:c,expires:s}},get:function(a,c){if(n.hasOwnProperty(a)&&!0!==c)return n[a].value;var e,g,h=document.cookie.split(";");for(g=0;g<h.length;g++)if(e=h[g].replace(/^\s+/gim,""),0===e.indexOf(a+"="))return decodeURIComponent(e.substring(a.length+1,e.length));return null},remove:function(a){this.set(a,"",-1);delete n[a]},purge:function(){for(var a in n)n.hasOwnProperty(a)&&(this.remove(a),delete n[a])},read:function(){return this.get.apply(this,arguments)},write:function(){return this.set.apply(this,
arguments)}},Cache:h,json:s,xml:{parse:function(a){var c;window.DOMParser?c=(new window.DOMParser).parseFromString(a,"text/xml"):(c=new window.ActiveXObject("Microsoft.XMLDOM"),c.async="false",c.loadXML(a));return c}}};for(var v in a)a.hasOwnProperty(v)&&(puredom[v]=a[v]);a=null})();window.puredom=window.puredom||{};puredom.EventEmitter=function(){this._eventRegistry=[]};
puredom.EventEmitter.prototype.addEventListener=function(a,e){var c,g;a=(a+"").toLowerCase().replace(/\s+/gim,"");if(-1<a.indexOf(",")){c=a.split(",");for(g=0;g<c.length;g++)this.addEventListener(c[g],e);return this}a=a.replace(/^on/,"");this._eventRegistry.push({type:a,handler:e});return this};puredom.EventEmitter.prototype.addListener=puredom.EventEmitter.prototype.addEventListener;puredom.EventEmitter.prototype.on=puredom.EventEmitter.prototype.addEventListener;
puredom.EventEmitter.prototype.removeEventListener=function(a,e){var c,g;a=(a+"").toLowerCase().replace(/\s+/gim,"");if(-1<a.indexOf(",")){c=a.split(",");for(g=0;g<c.length;g++)this.removeEventListener(c[g],e);return this}a=a.replace(/^on/,"");for(c=this._eventRegistry.length;c--;)if(g=this._eventRegistry[c],g.type===a&&g.handler===e){this._eventRegistry.splice(c,1);break}return this};puredom.EventEmitter.prototype.removeListener=puredom.EventEmitter.prototype.removeEventListener;
puredom.EventEmitter.prototype.fireEvent=function(a,e){var c,g,k=[];a=(a+"").toLowerCase().replace(/^on/,"");puredom.isArray(e)||(e=[e]);for(c=this._eventRegistry.length;c--&&!(g=this._eventRegistry[c],g.type===a&&(0===k.length&&(k.falsy=k.falsey=k.truthy=!0),g=g.handler.apply(this,e),k.push(g),!0===g?k.falsy=k.falsey=!1:!1===g&&(k.truthy=!1),!1===g)););return k};puredom.EventEmitter.prototype._fireEvent=puredom.EventEmitter.prototype.fireEvent;window.puredom=window.puredom||{};
puredom.net={HttpRequest:function(a){puredom.extend(this,a)},get:function(a,e,c){return this.request(puredom.extend({url:a,type:"GET",callback:e},c||{}))},post:function(a,e,c,g){return this.request(puredom.extend({url:a,type:"POST",post:e,callback:c},g||{}))},multiLoad:function(a,e){if(!a)return!1;var c=-1,g=a.length,k=[],m,p;m=function(g,h){if(g&&h){var s=a[c],v=h;s.process&&s.process.call&&(v=s.process(v),void 0===v&&(v=h));k.push(v);e&&e(!1,k,0,0);m=p=a=k=e=null}else p()};p=function(){c+=1;var k=
a[c];(k="string"===typeof k?{url:k}:k)?http.request(k,m):c<g?p():e(!1,null,null,"No resources were available.")};p();return!0},request:function(a,e){var c,g,k;if(!a.url)return!1;k=this;a=a||{};c=new puredom.net.HttpRequest({url:a.url,type:a.type||(a.post?"POST":"GET"),callback:a.callback||e||function(){},post:a.post,headers:a.headers});a.contentTypeOverride&&(c.contentTypeOverride=a.contentTypeOverride,delete a.contentTypeOverride);this.createXHR(c.url,function(a){c.request=a.xhr;c._xdrFrame=a.frame;
a=null;c.post&&"object"===puredom.typeOf(c.post)&&(c.post=puredom.parameterize(c.post),"?"===c.post.substring(0,1)&&(c.post=c.post.substring(1)));c.request.onreadystatechange=function(){var a;c.request._orig&&(c.request.readyState=c.request._orig.readyState,c.request.status=c.request._orig.status,c.request.responseText=c.request._orig.responseText,c.request.responseXML=c.request._orig.responseXML);if(4===c.request.readyState){c._xdrFrame&&setTimeout(function(){k._freeIframes.push(c._xdrFrame);k=null},
100);c.status=c.request.status;if(c.contentTypeOverride)a=c.contentTypeOverride.toLowerCase();else{try{a=c.request.getResponseHeader("Content-Type").toLowerCase()}catch(e){}a=a||""}c.responseText=c.request.responseText;if(a.match(/\/(json|javascript)$/gm)||"json"===a){c.responseType="json";a=c.responseJSON=null;try{a=c.responseJSON=JSON.parse(c.request.responseText.replace(/^[^\[\{]*(.*)[^\[\{]*$/g,"$1"))}catch(g){c.jsonParseError=!0}}else"application/xml"===a||"xml"===a?(c.responseType="xml",a=c.responseXML=
c.request.responseXML):(c.responseType="text",a=c.responseText);c.callback&&c.callback(400>c.request.status,a)}};c.request.open(c.type,c.url,!1!==c.async);c.request.setRequestHeader("content-type","application/x-www-form-urlencoded");c.request.setRequestHeader("x-requested-with","XMLHttpRequest");if(c.headers)for(g in c.headers)if(c.headers.hasOwnProperty(g))try{c.request.setRequestHeader(g,c.headers[g])}catch(e){}c.request.send(c.post||null)});return c},jsonp:function(){var a=function(){return a.get.apply(a,
arguments)},e=0;a.get=function(a,g,k){var m,p,n,h;"function"===puredom.typeOf(g)&&(k&&"object"===puredom.typeOf(k)&&(h=k),k=g,h&&(g=h));g=g||{};g.callback&&!k&&(k=g.callback);g.timeout||(g.timeout=10);a=a||g.url;if(!a)return!1;g.params&&puredom.parameterize&&(a+=(-1<a.indexOf("?")?"&":"?")+puredom.querystring.stringify(g.params));e+=1;g.callback=n="puredom_net_jsonp_"+e;window[g.callback]=function(a){var c;if(k){try{k(a)}catch(e){c=e}k=null}p&&(p.stop(),p=null);if(c)throw c;};a=-1<a.indexOf("{!callback}")?
a.replace("{!callback}",n):a+((0>a.indexOf("?")?"?":"&")+encodeURIComponent(g.callbackParam||"callback")+"="+encodeURIComponent(n));this._head||(this._head=(h=document.getElementsByTagName("head"))&&h[0]);m=puredom.el({type:"script",attributes:{src:a,async:"async",type:"text/javascript"},parent:this._head||document.body});p={id:n,stop:function(){p._timer&&clearTimeout(p._timer);window[n]=null;try{delete window[n]}catch(a){}k=null;m.attr("src","about:blank").remove();n=p=m=null}};g.timeout&&0<g.timeout&&
(p._timer=setTimeout(function(){k&&k({_requestTimedOut:!0,_jsonpTimedout:!0,success:!1,result:!1});p&&p.stop()},Math.round(1E3*g.timeout)));a=g=h=null;return p};return a}(),_freeIframes:[],_xhrIndex:0,createXHR:function(a,e){var c=!1,g=this,k,m,p,n,h,s;this._xhrIndex+=1;if(a&&(k=(k=/^[a-z]{3,9}\:\/\/([^\/\?#]+)/gim.exec(a))&&k[1])&&k!==location.hostname){c=!0;document.domain=location.hostname.match(/[^.]+\.[^.]+$/gim)[0];for(s=0;s<this._freeIframes.length;s++)if(this._freeIframes[s].getAttribute("data-xhr-domain")===
k){m=this._freeIframes.splice(s,1)[0];break}m?e(g._createXHRObj(m.contentWindow,m)):(m=document.createElement("iframe"),m.style.cssText="position:absolute; left:0; top:-1000px; width:1px; height:1px; border:none; overflow:hidden;",n=function(){var a,c;try{c=(a=m.contentWindow)&&a.document&&a.document.domain===document.domain&&a.document.body}catch(s){c=null}c&&c.innerHTML&&(clearInterval(h),m.onload=m.onerror=null,e(g._createXHRObj(a,m)),g=e=p=m=k=n=h=null)},m.onload=m.onerror=n,m.setAttribute("src",
location.protocol+"//"+k+"/xd_receiver.html"),m.setAttribute("role","presentation"),m.setAttribute("tabindex","-1"),m.setAttribute("data-xhr-domain",k),document.body.appendChild(m),h=setInterval(n,50))}if(!c)return p=this._createXHRObj(),e(p),p},_createXHRObj:function(a,e){var c;a=a||window;try{c=new a.XMLHttpRequest}catch(g){try{c=new a.ActiveXObject("Msxml2.XMLHTTP")}catch(k){c=new a.ActiveXObject("Microsoft.XMLHTTP")}}return{xhr:c,frame:e}}};window.puredom=window.puredom||{};
puredom.LocalStorage=function(a,e,c){var g=this;c=c||{};this.id=a;this.adapter=null;this.data={};c.adapter&&this.setAdapter(c.adapter);!this.adapter&&!1!==c.useBest&&this.useBestAdapter();this.adapter&&!1!==c.restore?this.restore(function(){e&&e(g);g=c=null}):e&&(e(g),g=null)};puredom.LocalStorage.prototype.commitDelay=100;puredom.LocalStorage.prototype.data={};
puredom.LocalStorage.prototype.setAdapter=function(a){var e=this.constructor.adapters,c=(a+"").toLowerCase(),g=!1,k=!1,m;for(m in e)if(e.hasOwnProperty(m)&&(m+"").toLowerCase()===c&&(g=!0,!0===e[m].test(this))){k=!0;this.adapterName=a;this.adapter=e[m];break}return!g?(puredom.log('puredom.LocalStorage :: Could not find "'+a+'" adapter.'),!1):!k?(puredom.log('puredom.LocalStorage :: "'+a+'" adapter test() failed: conditions for adapter use not met.'),!1):!0};
puredom.LocalStorage.prototype.getAdapter=function(){return this.adapterName};puredom.LocalStorage.prototype.useBestAdapter=function(){var a=this.constructor.adapters,e,c,g;for(g in a)if(a.hasOwnProperty(g)&&!0===a[g].test(this)&&(!e||(Math.round(e.rating)||0)<(Math.round(a[g].rating)||0)))e=a[g],c=g;if(e)this.adapterName=c,this.adapter=e;else return setTimeout(function(){throw"puredom.LocalStorage :: Could not find the best adapter.";},1),!1;return!0};
puredom.LocalStorage.prototype.getNamespace=function(a){var e=this,c;a+="";"."===a.substring(0,1)&&(a=a.substring(1));"."===a.substring(a.length-1)&&(a=a.substring(0,a.length-1));c=puredom.extend(new puredom.LocalStorage.NamespacedLocalStorage,{getAdapter:function(){return e.getAdapter()},getNamespace:this.getNamespace,getValue:function(c){return e.getValue(a+"."+c)},setValue:function(c,k){e.setValue(a+"."+c,k);return this},removeKey:function(c){e.removeKey(a+"."+c);return this},purge:function(){e.removeKey(a);
return this},getData:function(){return e.getValue(a)},restore:function(a){var c,m=this;a&&(c=function(){a(m);m=c=a=null});e.restore(c);return this},commit:function(a){var c,m=this;a&&(c=function(){a(m);m=c=a=null});e.commit(c);return this}});puredom.extend(c,{get:c.getValue,set:c.setValue,remove:c.removeKey});return c};puredom.LocalStorage.prototype.getData=function(){return this.data};puredom.LocalStorage.prototype.getValue=function(a){return puredom.delve(this.data,a)};
puredom.LocalStorage.prototype.setValue=function(a,e){var c=this.data,g=a.split("."),k;for(k=0;k<g.length-1;k++)c.hasOwnProperty(g[k])||(c[g[k]]={}),c=c[g[k]];void 0===e||null===e?(c[g[g.length-1]]=null,delete c[g[g.length-1]]):c[g[g.length-1]]=e;this.queueCommit();return this};puredom.LocalStorage.prototype.removeKey=function(a){this.setValue(a,void 0);return this};puredom.LocalStorage.prototype.get=puredom.LocalStorage.prototype.getValue;puredom.LocalStorage.prototype.set=puredom.LocalStorage.prototype.setValue;
puredom.LocalStorage.prototype.remove=puredom.LocalStorage.prototype.removeKey;puredom.LocalStorage.prototype.purge=function(){this.data={};this.queueCommit();return this};puredom.LocalStorage.prototype.restore=function(a){var e=this,c,g;if((c=this._adapterCall("load",function(c){e.data=g=c||{};a&&a(e);e=null}))&&!g)this.data=c,a&&a(this);c=g=null;return this};
puredom.LocalStorage.prototype.commit=function(a){var e=this;this._commitTimer&&(clearTimeout(this._commitTimer),this._commitTimer=null);this._adapterCall("save",this.data,function(){a&&a(e);e=null});return this};puredom.LocalStorage.prototype.queueCommit=function(){var a=this;this._commitTimer||(this._commitTimer=setTimeout(function(){a.commit();a=null},this.commitDelay))};
puredom.LocalStorage.prototype._adapterCall=function(a,e){if(this.adapter&&this.adapter[a])return this.adapter[a].apply(this.adapter,[this].concat(puredom.toArray(arguments).slice(1)))};puredom.LocalStorage.NamespacedLocalStorage=function(){};puredom.LocalStorage.adapters={};
puredom.LocalStorage.addAdapter=function(a,e){if(e.save)if(e.load)this.adapters[a]=e;else throw'puredom.LocalStorage :: Adapter "'+a+'" attempted to register, but does not provide a load() method.';else throw'puredom.LocalStorage :: Adapter "'+a+'" attempted to register, but does not provide a save() method.';};window.puredom=window.puredom||{};
puredom.date={now:Date.now?function(){return Date.now()}:function(){return+new Date},create:function(a){a?(a=(a+"").replace(/^([0-9]{4})\-([0-9]{2})\-([0-9]{2})T([0-9]{2})\:([0-9]{2})\:([0-9]{2})\.[0-9]{3}Z$/,"$1/$2/$3 $4:$5:$6"),a=new Date(a)):a=new Date;return a},parse:function(a,e){var c,g,k,m,p;function n(a,e){if(!1===e||!0===e)c=!0===e;if(a||0===a)g=a;a=g;12>g&&c&&(a-=12);var k=h.getDate();12===g&&!1===c?(0!==h.getHours()||e===!!e)&&h.setHours(0):(h.setHours(a),h.setDate(k))}e=e||"%d/%m/%Y";
var h=new Date(0);p=m=k=g=c=void 0;var s={H:[/^[0-9]{1,2}/g,function(a){a=Math.round(a);n(a)}],I:[/^[0-9]{1,2}/g,function(a){a=Math.round(a);n(a)}],p:[/^[AP]M/gi,function(a){n(null,"pm"===a.toLowerCase())}],M:[/^[0-9]{1,2}/g,function(a){h.setMinutes(Math.round(a))}],a:[/^(Mon|Tue(s?)|Wed|Thu|Fri|Sat|Sun)/i,function(){}],A:[/^(Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday)/i,function(){}],d:[/^[0-9]{1,2}/g,function(a){k=Math.round(a);h.setDate(k)}],m:[/^[0-9]{1,2}/g,function(a){m=Math.round(a)-
1;h.setMonth(m)}],B:[RegExp("^("+this.months.join("|")+")","gi"),function(a){m=date._getMonthIndex(a);h.setMonth(m)}],b:[/^(Jan|Feb|Mar|Apr|May|Jun(e?)|Jul(y?)|Aug|Sep(t?)|Oct|Nov|Dec)/gi,function(a){m=date._getMonthIndex(a);h.setMonth(m)}],y:[/^[0-9]{2}/g,function(a){a=Math.round(a)+1900;1950>a&&(a+=100);h.setFullYear(a)}],Y:[/^[0-9]{4}/g,function(a){p=Math.round(a);h.setFullYear(p)}]},v,l,t;s.l=s.I;s.e=s.d;s.P=s.p;s.h=s.b;for(v=0;v<e.length;v++)if("%"===e.charAt(v))for(t in l=null," "===a.charAt(0)&&
"%"===e.charAt(v)&&(a=a.substring(1)),s){if(s.hasOwnProperty(t)&&e.substring(v+1,v+1+t.length)===t){l=s[t];a=a.replace(l[0],function(a){l[1](a);return""});v+=l.length-1;break}}else a.charAt(0)===e.charAt(v)&&(a=a.substring(1));(m||0===m)&&h.setMonth(m);(p||0===p)&&h.setFullYear(p);return h},unformat:function(){return this.parse.apply(this,arguments)},format:function(a,e){e=e||"%d/%m/%Y";if(!a||a.constructor!==Date||!a.toDateString)return!1;var c=a.toDateString();if(!c||"invalid date"===c.toLowerCase()||
"NaN"===c)return!1;var c=c.split(" "),g=a.getHours(),k=(g+11)%12+1,m=a.getMonth()+1,p={H:g,I:(10>k?"0":"")+k,l:k,p:11<g?"PM":"AM",P:11<g?"pm":"am",M:(10>a.getMinutes()?"0":"")+a.getMinutes(),S:(10>a.getSeconds()?"0":"")+a.getSeconds(),a:c[0],A:this.weekdays[a.getDay()],d:c[2],e:Math.round(c[2]),m:(10>m?"0":"")+m,B:this.months[Math.round(c[1])],b:c[1],h:c[1],y:c[3].substring(2),Y:c[3]};return e.replace(/%[HIlpPMSaAdemBbhyY]/gm,function(a){var c=p[a.charAt(1)+""];return c||0===c||!1===c?c:a})},_getMonthIndex:function(a){a=
a.substring(0,3).toLowerCase();for(var e=0;e<this.months.length;e++)if(this.months[e].substring(0,3).toLowerCase()===a)return e;return-1},weekdays:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),months:"January February March April May June July August September October November December".split(" ")};
puredom.LocalStorage.addAdapter("UserData",{defaultName:"db",rating:20,test:function(){return/\bMSIE\s[1-6](\.[0-9]*)?/gim.test(navigator.userAgent+"")?!1:"undefined"!==typeof document.body.addBehavior},load:function(a,e){var c=this._getKey(a),c=this._getStore(c),g,k;c&&(g=c.getAttribute("puredomlocalstorage"));g&&(k=puredom.json.parse(g));e&&e(k);return k},save:function(a,e,c){a=this._getKey(a);var g=this._getStore(a),k=!1;g&&"save"in g&&(void 0===e?g.removeAttribute?g.removeAttribute("puredomlocalstorage"):
g.setAttribute("puredomlocalstorage",""):g.setAttribute("puredomlocalstorage",puredom.json.stringify(e)),g.save(a),k=!0);c&&c(k);return k},_getStore:function(a){var e;this.stores||(this.stores={});e=this.stores[a];e||(e=this.stores[a]=document.getElementById(a),e||(e=this.stores[a]=document.createElement("span"),e.style.position="absolute",e.style.top="-100px",e.style.left="0",e.style.behavior="url('#default#userData')",document.body.appendChild(e)));"true"!==e.getAttribute("data-tdlsud-loaded")&&
(e.setAttribute("data-tdlsud-loaded","true"),e.load(a));return e},_getKey:function(a){return"ieud"+(a.id||this.defaultName||"")+""}});
puredom.LocalStorage.addAdapter("LocalStorage",{defaultName:"db",rating:60,test:function(){var a="localStorage"in window&&"function"===typeof window.localStorage.hasOwnProperty,e,c=puredom.json({a:"a",b:4/3,c:!0,d:null});if(a)try{e=localStorage.__test,localStorage.__test=c,localStorage.__test!==c&&(a=!1),localStorage.__test=e,void 0===e&&delete localStorage.__test}catch(g){a=!1}return a},load:function(a,e){var c=this._getKey(a),g;localStorage.hasOwnProperty(c)&&(g=puredom.json.parse(localStorage[c]));
e&&e(g);return g},save:function(a,e,c){a=this._getKey(a);void 0===e?delete localStorage[a]:localStorage[a]=puredom.json.stringify(e);c&&c(!0);return!0},_getKey:function(a){return(a.id||this.defaultName||"")+""}});
puredom.LocalStorage.addAdapter("cookie",{defaultName:"db",rating:0,test:function(){return puredom.cookies&&puredom.cookies.get&&"cookie"in document?!0:!1},load:function(a,e){var c=puredom.cookies.get(a.id||this.defaultName),g;c&&(g=puredom.json(c));e&&e(g);return g},save:function(a,e,c){puredom.cookies.set(a.id||this.defaultName,puredom.json(e));c&&c(!0)}});