this.JSON||(this.JSON={});
(function(){function a(a){return a<10?"0"+a:a}function e(a){j.lastIndex=0;return j.test(a)?'"'+a.replace(j,function(a){var c=m[a];return typeof c==="string"?c:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function c(a,g){var k,q,o,j,m=l,w,s=g[a];s&&(typeof s==="object"&&typeof s.toJSON==="function")&&(s=s.toJSON(a));typeof h==="function"&&(s=h.call(g,a,s));switch(typeof s){case "string":return e(s);case "number":return isFinite(s)?String(s):"null";case "boolean":case "null":return String(s);
case "object":if(!s)return"null";l=l+n;w=[];if(Object.prototype.toString.apply(s)==="[object Array]"){j=s.length;for(k=0;k<j;k=k+1)w[k]=c(k,s)||"null";o=w.length===0?"[]":l?"[\n"+l+w.join(",\n"+l)+"\n"+m+"]":"["+w.join(",")+"]";l=m;return o}if(h&&typeof h==="object"){j=h.length;for(k=0;k<j;k=k+1){q=h[k];if(typeof q==="string")(o=c(q,s))&&w.push(e(q)+(l?": ":":")+o)}}else for(q in s)if(Object.hasOwnProperty.call(s,q))(o=c(q,s))&&w.push(e(q)+(l?": ":":")+o);o=w.length===0?"{}":l?"{\n"+l+w.join(",\n"+
l)+"\n"+m+"}":"{"+w.join(",")+"}";l=m;return o}}if(typeof Date.prototype.toJSON!=="function"){Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+a(this.getUTCMonth()+1)+"-"+a(this.getUTCDate())+"T"+a(this.getUTCHours())+":"+a(this.getUTCMinutes())+":"+a(this.getUTCSeconds())+"Z":null};String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()}}var g=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
j=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,l,n,m={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},h;if(typeof JSON.stringify!=="function")JSON.stringify=function(a,e,k){var g;n=l="";if(typeof k==="number")for(g=0;g<k;g=g+1)n=n+" ";else typeof k==="string"&&(n=k);if((h=e)&&typeof e!=="function"&&(typeof e!=="object"||typeof e.length!=="number"))throw Error("JSON.stringify");return c("",{"":a})};
if(typeof JSON.parse!=="function")JSON.parse=function(a,c){function h(a,e){var g,j,q=a[e];if(q&&typeof q==="object")for(g in q)if(Object.hasOwnProperty.call(q,g)){j=h(q,g);j!==void 0?q[g]=j:delete q[g]}return c.call(a,e,q)}var e,a=String(a);g.lastIndex=0;g.test(a)&&(a=a.replace(g,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,
"]").replace(/(?:^|:|,)(?:\s*\[)+/g,""))){e=eval("("+a+")");return typeof c==="function"?h({"":e},""):e}throw new SyntaxError("JSON.parse");}})();"function"!==typeof Date.now&&(Date.now=function(){return(new Date).getTime()});window._previousPureDom=window.puredom;
(function(){var a=function(){return h.puredom.apply(h,arguments)},e={baseAnimationInterval:20,allowCssTransitions:true,easingMethods:{ease:function(a){return(Math.sin(a*Math.PI-Math.PI/2)+1)/2},"ease-in-out":function(a){return(Math.sin(a*Math.PI-Math.PI/2)+1)/2},"ease-in-out-2":function(a){return this["ease-in-out"](this["ease-in-out"](a))},"ease-in-out-3":function(a){return this["ease-in-out"](this["ease-in-out"](this["ease-in-out"](a)))}}},c=false,g,j,l=e.constructor,n,m,h={oninit:[],animationTimes:{fast:150,
medium:450,slow:1E3},animationTimeScale:1,registeredEventCount:0,html5elements:["abbr","article","aside","audio","canvas","datalist","details","figcaption","figure","footer","header","hgroup","mark","meter","nav","output","progress","section","summary","time","video"],support:{html5:true,querySelectorAll:!!("querySelectorAll"in document),filters:false,webkitMultitouch:!!("createTouch"in document)},regex:{css3AutoPrefix:/([\s\;\/\*])(box\-shadow|text\-shadow|border\-radius)\:([^\;]*)(\;|$)/gim,css3VendorPrefix:/\b\-(moz|webkit|ms|o|vendor)\-/gim,
templateFieldToken:/([^\\]?)\{([a-z0-9A-Z\$_\.]+)(\|[^\}]*?)?\}/gm,parseObjectNameFromString:/^\[object ([^\s]+)\]$/gim,autoDetectHTMLContent:/(<[a-z]|&[a-z#0-9]{1,10};)/gim,whitespaceCharacters:/\s/,getNumericCSSValue:/[^0-9\.\-]/gm,getCSSValueUnits:/([a-z]+|%)$/,getNonIntegerCharsSigned:/[^0-9\.\-]/gm,getUpperCaseAlphaChars:/[A-Z]/gm}};if(navigator.userAgent.match(/\b(iOS|Android|WebOS|iPhone|iPod|iPad)\b/gim)){a.allowCssTransitions=false;a.baseAnimationInterval=50;h.animationTimeScale=1.5}if(navigator.userAgent.match(/\b(webkit|applewebkit|chrome|chromium|khtml)\b/gim)){g=
"-webkit";j="Webkit"}else if(navigator.userAgent.match(/\bopera\b/gim)){g="-o";j="O"}else if(navigator.userAgent.match(/\bgecko\b/gim)){g="-moz";j="Moz"}else if(navigator.userAgent.match(/\bmsie\s*?(8|9|[1-9][0-9]+)\b/gim)){g="-ms";j="Ms"}else if(navigator.userAgent.match(/\bmsie\s*?[4-8]\b/gim)){h.support.filters=true;h.support.filterProperty="filter"}var p=void 0,p=void 0,p=document.createElement("div");p.innerHTML="<nav></nav>";h.support.html5=p.childNodes.length>0;if(!h.support.html5){h.html5frag=
document.createDocumentFragment();for(p=h.html5elements.length;p--;)h.html5frag.createElement(h.html5elements[p]);h.html5div=document.createElement("div");h.html5frag.appendChild(h.html5div)}m=function(){var a=document.body;n=a.textContent!==void 0&&"textContent"||a.innerText&&"innerText"||"innerHTML";m=null;return n};a.extend=function(a){var b,f,d,a=a||{};for(b=1;b<arguments.length;b++)if(d=arguments[b]){for(f in d)d.hasOwnProperty(f)&&(a[f]=d[f]);if(typeof d.toString==="function"&&d.toString!==
Object.prototype.toString)a.toString=d.toString}return a};a.mixin=function(a){var b,f,d,a=a||{};for(b=1;b<arguments.length;b++)if(d=arguments[b])for(f in d)d.hasOwnProperty(f)&&!a.hasOwnProperty(f)&&(a[f]=d[f]);return a};a.strip=function(a,b){for(var f in a)if(b===true||a.hasOwnProperty(f))a[f]=null};a.delve=function(a,b,f,d){var i=0,b=b.split(".");for(f===true&&b.splice(0,1);i<b.length&&a&&a.hasOwnProperty(b[i]);){a=a[b[i]];i=i+1}if(i>=b.length||d===true&&i>0)return a};a.flattenObj=function(c,b,
f,d){var i,u,b=b||"",f=f||0,d=d||{};for(i in c)if(c.hasOwnProperty(i)){u=b?b+"_"+i:i;a.isScalar(c[i])?d[u]=c[i]:a.flattenObj(c[i],u,f+1,d)}if(!f)return d};a.template=function(c,b,f){var d;if(f!==false&&a.i18n)d=a.i18n;return(c+"").replace(h.regex.templateFieldToken,function(f,u,c,h){if(u!=="\\"&&c)if(f=a.delve(b,c)){d&&(f=d(f)||f);h&&h.substring(0,1)==="|"&&(f=a.text.filter(f,h.substring(1)));f=u+f}else f=u;else f=u;return f})};a.inherits=function(a,b){function f(){}f.prototype=b.prototype;var d=
a.prototype;a.prototype=new f;puredom.extend(a.prototype,d);a.prototype.constructor=a;a.prototype.__super=b};a.typeOf=function(a){if(a===void 0)return"undefined";if(a===null)return"null";if(a){if(a.constructor===l)return"object";if(Object.prototype.toString.call(a)==="[object Array]")return"array"}return Object.prototype.toString.call(a).replace(h.regex.parseObjectNameFromString,"$1").toLowerCase()};a.isScalar=function(c){c=a.typeOf(c);return c==="undefined"||c==="null"||c==="number"||c==="string"||
c==="boolean"?true:false};if(!Array.prototype.indexOf||[a].indexOf(a)!==0)try{Array.prototype.indexOf=function(a){for(var b=0;b<this.length;b++)if(this[b]===a)return b;return-1}}catch(t){}a.toArray=function(a){var b=[],f=a&&a.length;if(f||f===0)for(;f--;)b[f]=a[f];else for(f=0;;){if(a.hasOwnProperty&&a.hasOwnProperty(f))b.push(a[f]);else if(a.hasOwnProperty&&a.hasOwnProperty(f+""))b.push(a[f+""]);else break;f=f+1}return b};a.isArray=function(c){return a.typeOf(c)==="array"};a.hasOwnProperty=function(a,
b){return Object.prototype.hasOwnProperty.call(a,b)};a.forEach=a.foreach=function(c,b){var f,d;if(a.isArray(c))for(f=0;f<c.length;f++){d=b(c[f],f);if(d===false)break}else for(f in c)if(c.hasOwnProperty(f)){d=b(c[f],f);if(d===false)break}return c};a.setInnerHTML=function(a,b){var f,d;if(h.support.html5)a.innerHTML=b||"";else{a.innerHTML="";h.html5div.innerHTML=b||"";f=document.createDocumentFragment();for(d=h.html5div.childNodes.length;d--;)f.appendChild(h.html5div.firstChild);a.appendChild(f)}};a.createElement=
function(c,b){var f,d,i,u,c=c||{};f=document.createElement(c.type||"div");b=b||c.parent;if(c.insertBefore&&c.insertBefore.constructor===a.NodeSelection)c.insertBefore=c.insertBefore._nodes[0];if(!b&&c.insertBefore)b=c.insertBefore.parentNode;for(d in c)if(a.hasOwnProperty(c,d))if((d+"").substring(0,2).toLowerCase()==="on")a.addEvent(f,d.substring(2),c[d]);else if(d==="css"||d==="cssText"){if(g){c[d]=c[d].replace(h.regex.css3AutoPrefix,"$1"+g+"-$2:$3; $2:$3;");c[d]=c[d].replace(h.regex.css3VendorPrefix,
"-"+g+"-")}f.style.cssText=c[d]}else if(d==="html"||d==="innerHTML")a.setInnerHTML(f,c[d]);else if(d==="attributes")for(i in c[d])a.hasOwnProperty(c[d],i)&&f.setAttribute(i,c[d][i]);else if(d!=="parent"&&d!=="children"&&d!=="insertBefore"&&d!=="type"&&d!=="children"&&d!=="html"&&d!=="innerHTML")if(document.all)try{f[d]=c[d]}catch(e){a.log(d)}else f[d]=c[d];if(b){if(c.insertBefore)try{b.insertBefore(f,c.insertBefore);u=true}catch(k){u=false}u||b.appendChild(f)}if(c.children&&a.isArray(c.children)){i=
document.createDocumentFragment();for(d=0;d<c.children.length;d++)a.createElement(c.children[d],i);f.appendChild(i)}return f};a.NodeSelection=function b(f){var d;this._results=[];this._nodes=[];this._animations=[];if(f)if(a.isArray(f))for(d=0;d<f.length;d++)f[d]&&(f[d].constructor===b&&f[d]._nodes?this._nodes.push(f[d]._nodes[0]):this._nodes.push(f[d]));else this._nodes.push(f)};a.extend(a.NodeSelection.prototype,{_results:[],_nodes:[],_animations:[],describe:function(){var b=[];this.each(function(a){var d=
"<"+a.nodeName(),i=a.prop("id"),u=a.prop("className");i&&(d=d+(' id="'+i+'"'));u&&(d=d+(' class="'+u+'"'));d=d+">";d=a._nodes[0].childNodes.length===1&&a._nodes[0].childNodes[0].nodeType===3?d+a.text().replace(/(\r|\n)/gim,decodeURIComponent("%E2%86%A9")).replace(/\t/gim,decodeURIComponent("%E2%86%92")):d+("["+a.children().count()+" children]");d=d+("</"+a.nodeName()+">");b.push(d)});return b},toString:function(){return this.describe().join(", ")},toSource:function(){return this._nodes},getResult:function(b){b=
Math.round(b)||0;return this._results[this._results.length-b-1]},pushResult:function(b){this._results.push(b);return this},each:function(b){return this._each(b,true)},_each:function(b,f,d){var i=this._nodes.slice(0,this._nodes.length),u,c,h;for(u=0;u<i.length;u++){c=u;d===true&&(c=i.length-c-1);h=i[c];f===true&&(h=new a.NodeSelection(h));b.call(this,h,c)}return this},wait:function(b,a){var d=this;a&&setTimeout(function(){a.apply(d);d=a=null},Math.abs(b));return this},nodeName:function(){var b=this._nodes[0],
a=b&&b.nodeName&&b.nodeName.toLowerCase();return b===window?"#window":a?a:null},uuid:function(){return this._nodes[0]&&h.nodeToId(this._nodes[0])||null},text:function(b){if(arguments.length===0)return this._nodes[0]&&this._nodes[0][n||m()]||"";b=b+"";this._each(function(a){a[n||m()]=b});return this},html:function(b,f){if(arguments.length===0)return this._nodes[0]&&this._nodes[0].innerHTML||"";b=b+"";h.regex.autoDetectHTMLContent.lastIndex=0;h.regex.autoDetectHTMLContent.test(b)&&f!==true?this._each(function(d){a.setInnerHTML(d,
b)}):this._each(function(a){a[n||m()]=b});return this},css:function(b,f){var d,i=this,f=f||{};d=a.typeOf(f.tween);if(d==="string"&&f.tween!=="none"||d==="number"&&f.tween>0){d=(f.tween+"").replace(h.regex.whitespaceCharacters,"").split(",");var c,e,k=0,g=0;e=function(b){g=g+1;if(g>=k){e=null;f.callback&&f.callback(b);i=null}};for(c in b)if(b.hasOwnProperty(c)){k=k+1;this.animateCss(c,b[c],d[0],d[1],e)}}else{this._each(function(d){a.applyCss(d,b)});f.callback?setTimeout(function(){f.callback(i);i=
null},1):i=null}return this},show:function(){this.css({display:"",visibility:"visible"});this._each(function(b){if(b.style.display==="none"||a.nodeStyle(b,"display")==="none")b.style.display="block"});return this},hide:function(b){return this.css(b===false?{visibility:"hidden"}:{display:"none"})},fadeIn:function(b,f){var d=parseFloat(this.getStyle("opacity")||"0")||0,i=1;if(this.getStyle("display")==="none"||this.getStyle("visibility")==="hidden"){this.getStyle("opacity")&&(d>0&&d<1)&&(i=d);d=0;this.css({opacity:0})}if(a.typeOf(b)===
"function")b=f=b;if(d>=1||b==0||b===false){this.css({opacity:i}).show();setTimeout(f,0);return this}this.css({opacity:i},{tween:b||"medium",callback:function(a){f&&f(a);b=f=null}}).show();return this},fadeOut:function(b,f,d){var i=parseFloat(this.getStyle("opacity")||"1")||1;if(a.typeOf(b)==="function")b=f=b;if(a.typeOf(f)==="boolean"){d=f;f=null;a.typeOf(d)==="function"&&(f=d)}if(i<=0||this.getStyle("display")==="none"||this.getStyle("visibility")==="hidden"||b===0||b===false){this.css({opacity:0}).hide(d);
setTimeout(f,0);return this}this.css({opacity:0},{tween:b||"medium",callback:function(a){a.hide(d).css({opacity:i});f&&f(a);b=f=null}});return this},animateCSS:function(){var b,f,d,i;b=function(b,d,f,i,c){var e=[],k=[],g,o,j,b=b.toLowerCase();if(d!=="auto"){g=parseFloat((d+"").replace(h.regex.getNumericCSSValue,""))||0;o=(j=a.typeOf(d)==="string"&&d.match(h.regex.getCSSValueUnits))&&j[0]||"px";b==="opacity"&&(o="")}else o=b==="opacity"?"":"px";this._each(function(f,i){var c,j;c={};var q;e[i]=parseFloat((a.nodeStyle(f,
b)+"").replace(h.regex.getNonIntegerCharsSigned,""))||0;if(d==="auto"||d===""){q=f.style.visibility||"";c[b]=d;c.visibility="hidden";a.applyCss(f,c);c=a.nodeStyle(f,b);if(c===d||c.indexOf("px")<c.length-3){c=b.substring(0,1).toUpperCase()+b.substring(1).toLowerCase();c=f["offset"+c]+"px"}j=a.typeOf(c)==="string"&&c.match(h.regex.getCSSValueUnits);k[i]={_actualTarget:d,numericTargetValue:parseFloat((c+"").replace(h.regex.getNumericCSSValue,""))||0,units:b==="opacity"?"":j&&j[0]||"px"};setTimeout(function(){f.style.visibility=
q;f=null},51);c=c=j=null}else k[i]={numericTargetValue:g,units:o}});return this.animate(function(d){this._each(function(f,i){var c={},h=d*(k[i].numericTargetValue-e[i])+e[i],g=k[i].units;if(g==="px")h=Math.round(h);else{h=parseFloat(h);h=h%1===0?Math.round(h):h.toFixed(2)}c[b]=h+g;a.applyCss(f,c)})},f,i,function(d){d._each(function(d,f){var i={};if(k[f]._actualTarget){i[b]=k[f]._actualTarget;a.applyCss(d,i)}});c.apply(d,arguments)})};f=function(b,d,f,i,c){var e=this._createAnimationObj(function(){},
f,i,c),k=this,g={},o={},b=(b+"").replace(h.regex.getUpperCaseAlphaChars,"-$1").toLowerCase();a.typeOf(d)==="number"&&(b+"").toLowerCase()!=="opacity"&&(d=d+"px");g[b]={duration:e.duration,timingFunction:e.easing};o[b]=d;setTimeout(function(){k._each(function(b){a.updateCssTransitions(b,g);a.applyCss(b,o);h.incrementAnimationCount(b)});e._cb=function(){if(e){var d={};d[b]=null;k._each(function(b){a.updateCssTransitions(b,d);h.decrementAnimationCount(b)});e.callback&&e.callback(k);for(var f in e)if(e.hasOwnProperty(f))try{delete e[f]}catch(i){}}e=
o=c=k=null};setTimeout(e._cb,(parseInt(e.duration,10)||0)+20)},10)};i=function(){return d=document.body.style[j+"Transition"]!==void 0||document.body.style.transition!==void 0};return function(c){a.typeOf(d)!=="boolean"&&i();a.allowCssTransitions!==false&&d?f.apply(this,arguments):b.apply(this,arguments);return this}}(),animate:function(b,f,d,i){if(b){var c=this,e=this._createAnimationObj.apply(this,arguments),k;this._each(function(b){h.incrementAnimationCount(b)});k=function(b){e.frameTime=b;e.position=
e.frameTime-e.start;e.fraction=e.position/e.duration;if(e.position>=e.duration){e.fraction=1;e.position=e.duration}else if(e.easingMethod)e.fraction=e.easingMethod.call(a.easingMethods,e.fraction,e);e.animator.call(c,e.fraction,e);if(e.fraction===1){for(b=c._animations.length;b--;)if(c._animations[b]===e){c._animations.splice(b,1);break}e.callback&&setTimeout(function(){c._each(function(b){h.decrementAnimationCount(b)});e.callback.call(c,c,e);c=e=null},10)}else e.timer=a.animationFrame.getTimer(k,
a.baseAnimationInterval||10)};a.animationFrame.getTimer(k,a.baseAnimationInterval||10);this._animations.push(e)}return this},_createAnimationObj:function(b,f,d,i){b={animator:b,duration:f,easing:a.typeOf(d)==="string"?d:"ease",callback:i,start:a.animationFrame.getStartTime(),frameTime:null};if(a.typeOf(b.duration)==="string")switch(b.duration.toLowerCase()){case "long":case "slow":b.duration=h.animationTimes.slow;break;case "short":case "fast":b.duration=h.animationTimes.fast;break;default:b.duration=
parseInt(b.duration)||h.animationTimes.medium}else b.duration=Math.round(b.duration)||h.animationTimes.medium;if(h.animationTimeScale)b.duration=b.duration*h.animationTimeScale;b.easing&&a.easingMethods.hasOwnProperty(b.easing)?b.easingMethod=a.easingMethods[b.easing]:b.easing=null;return b},classify:function(b){var f=[],d=arguments[0]==="{*^de^*}"?"removeClass":"addClass",i,c;for(i=0;i<arguments.length;i++)if(a.isArray(arguments[i]))for(c=0;c<arguments[i].length;c++)f.push(arguments[i][c]);else f.push(arguments[i]);
this._each(function(b){a[d](b,f)});return this},declassify:function(b){var a=["{*^de^*}"].concat(Array.prototype.slice.call(arguments,0));return this.classify.apply(this,a)},hasClass:function(b,a){var d=a!==true;this._each(function(i){i=(" "+i.className+" ").indexOf(" "+b+" ")>-1;a===true?i&&(d=true):i||(d=false)});return d},setOpacity:function(b){this._each(function(f){a.setOpacity(f,b)});return this},sumOf:function(b){var f=0,d=Array.prototype.slice.call(arguments,1);this.constructor.prototype.hasOwnProperty(b)&&
this._each(function(i){i=new a.NodeSelection(i);f=f+i[b].apply(i,d)});return f},height:function(b,f){var d,i=0;if(a.typeOf(b)==="object"&&!f){f=b;b=null}f=f||{};if(b||b===0){b=b+"";if(b==="auto")d="";else{d=/^([\-0-9\.]+)(.*?)$/.exec(b);b=Math.round(d&&d[1]||b)||0;d=d&&d[2]||"px"}this.css({height:b+d});return this}this._each(function(b){i=i+(parseInt(b.offsetHeight,10)||0);if(f.border!==true){i=i-(parseInt((a.nodeStyle(b,"border-top-width")+"").replace(h.regex.getNonIntegerCharsSigned,""),10)||0);
i=i-(parseInt((a.nodeStyle(b,"border-bottom-width")+"").replace(h.regex.getNonIntegerCharsSigned,""),10)||0)}if(f.margin===true){i=i+(parseInt((a.nodeStyle(b,"margin-top")+"").replace(h.regex.getNonIntegerCharsSigned,""),10)||0);i=i+(parseInt((a.nodeStyle(b,"margin-bottom")+"").replace(h.regex.getNonIntegerCharsSigned,""),10)||0)}if(f.padding===false){i=i-(parseInt((a.nodeStyle(b,"padding-top")+"").replace(h.regex.getNonIntegerCharsSigned,""),10)||0);i=i-(parseInt((a.nodeStyle(b,"padding-bottom")+
"").replace(h.regex.getNonIntegerCharsSigned,""),10)||0)}});return i},width:function(b,f){var d,i=0;if(a.typeOf(b)==="object"&&!f){f=b;b=null}f=f||{};if(b||b===0){b=b+"";if(b==="auto")d="";else{b=(d=/^([\-0-9\.]+)(.*?)$/.exec(b))&&d[1]||b;d=d&&d[2]||"px"}this.css({width:b+d});return this}this._each(function(b){i=i+(parseInt(b.offsetWidth,10)||0);if(f.border!==true){i=i-(parseInt((a.nodeStyle(b,"border-left-width")+"").replace(h.regex.getNonIntegerCharsSigned,""),10)||0);i=i-(parseInt((a.nodeStyle(b,
"border-right-width")+"").replace(h.regex.getNonIntegerCharsSigned,""),10)||0)}if(f.margin===true){i=i+(parseInt((a.nodeStyle(b,"margin-left")+"").replace(h.regex.getNonIntegerCharsSigned,""),10)||0);i=i+(parseInt((a.nodeStyle(b,"margin-right")+"").replace(h.regex.getNonIntegerCharsSigned,""),10)||0)}if(f.padding===false){i=i-(parseInt((a.nodeStyle(b,"padding-left")+"").replace(h.regex.getNonIntegerCharsSigned,""),10)||0);i=i-(parseInt((a.nodeStyle(b,"padding-right")+"").replace(h.regex.getNonIntegerCharsSigned,
""),10)||0)}});return i},x:function(b){var a=this._nodes[0],d=null;if(a){d=a.offsetLeft;if(b===true)for(;(a=a.parentNode)&&a!==document;)d=d+(parseFloat(a.offsetLeft)||0)}return d},y:function(b){var a=this._nodes[0],d=null;if(a){d=a.offsetTop;if(b===true)for(;(a=a.parentNode)&&a!==document;)d=d+(parseFloat(a.offsetTop)||0)}return d},position:function(b,a,d,i){var c,i=i||"px";if(arguments.length<1||arguments.length===1&&arguments[0]===true)return{x:this.x(arguments[0]===true),y:this.y(arguments[0]===
true)};c={};if(puredom.typeOf(b)==="number")c.left=b+i;else if(puredom.typeOf(b)==="string")c.left=b;if(puredom.typeOf(a)==="number")c.top=a+i;else if(puredom.typeOf(a)==="string")c.top=a;this.css(c,d);return this},scrollLeft:function(b){if(b||b===0){a.typeOf(b)!=="number"&&(b=Math.round((b+"").replace(h.regex.getNonIntegerCharsSigned,"")));this._each(function(a){a.scrollLeft=b})}else return this._nodes&&this._nodes[0]&&this._nodes[0].scrollLeft||0},scrollTop:function(b){if(b||b===0){a.typeOf(b)!==
"number"&&(b=Math.round((b+"").replace(h.regex.getNonIntegerCharsSigned,"")));this._each(function(a){a.scrollTop=b})}else return this._nodes&&this._nodes[0]&&this._nodes[0].scrollTop||0},focus:function(){this._each(function(b){b.focus&&b.focus()});return this},blur:function(){this._each(function(b){b.blur&&b.blur()});return this},selectAll:function(){this._each(function(b){b.SelectAll&&b.SelectAll();b.select&&b.select();if(b.selectionStart&&b.hasOwnProperty("value")){b.selectionStart=0;b.selectionEnd=
b.value.length}})},getStyle:function(b,f){var d=[];this._each(function(f){d.push(a.nodeStyle(f,b)||null)});if(f===false){this.pushResult(d);return this}return d.length<=1?d[0]:d},value:function(b,f){f=f||{};if(b!==null&&b!==void 0&&arguments.length>0){this._each(function(d){var c=(d.nodeName+"").toLowerCase(),e=(d.getAttribute("type")||"").toLowerCase();if(c==="input"&&(e==="checkbox"||e==="radio"))d.checked=!!b;d.value=b;f.fireChange!==false&&a.fireEvent({type:"change",target:d,value:b})});return this}var d=
[];this._each(function(b){var f=(b.nodeName+"").toLowerCase(),c=(b.getAttribute("type")||"").toLowerCase(),e;if(f==="input"&&(c==="checkbox"||c==="radio"))d.push(!!b.checked);else if(f==="select"){e=b.multiselect||b.multiSelect?[]:null;a.el(b).query("option")._each(function(b){if(b.selected||b.checked)a.isArray(e)?e.push(b.value):e=b.value});d.push(e)}else d.push(b.value)});return d.length<2?d[0]||null:d},attr:function(b,f,d){var i=[],c,e;if(arguments.length===0){i={};for(c=this._nodes[0].attributes.length;c--;){e=
this._nodes[0].attributes[c];e.specified&&(i[e.name||e.nodeName]=e.value||e.nodeValue)}return i}if(arguments.length>1){if(a.typeOf(b)==="object"){for(c in b)typeof c==="string"&&b.hasOwnProperty(c)&&this.attr(i,b[c]);return this}return this._each(function(a){try{a.setAttribute(b,f);a.removeAttribute&&(f===null||f===void 0)&&a.removeAttribute(b)}catch(d){}})}this._each(function(a){a=a.getAttribute(b);typeof a!=="string"&&(a=null);i.push(a)});if(d===false){this.pushResult(i);return this}return i.length<=
1?i[0]:i},prop:function(b,a,d){var i=[];if(arguments.length>1)return this._each(function(d){d[b]=a;if(a===void 0)try{delete d[b]}catch(i){}});this._each(function(a){var d;try{d=a[b]}catch(f){console.log("NodeSelection.prop("+b+") :: Access Error",f)}i.push(d||null)});if(d===false){this.pushResult(i);return this}return i.length<=1?i[0]:i},enable:function(){this.attr("disabled",null);this.declassify("_puredom_disabled");return this},disable:function(){this.attr("disabled","disabled");this.classify("_puredom_disabled");
return this},enabled:function(b){if(b===true||b===false){this[b?"enable":"disable"]();return this}return this.attr("disabled")!=="disabled"&&this.prop("disabled")!==true&&!this.hasClass("_puredom_disabled")},addEvent:function(b,f,d){this._each(function(i){a.addEvent(i,b,f,d)});return this},removeEvent:function(b,f,d){this._each(function(i){a.removeEvent(i,b,f,d)});return this},fireEvent:function(b,f){this._each(function(d){a.fireEvent(a.extend({},f||{},{type:b,target:d}))});return this},_removeAllEvents:function(b){var a;
this._each(function(b){h.wrappedEventListener.destroyObjHandlers(b,true)});a=this.children();b===true&&a.count()>0&&a._removeAllEvents(true);a=b=null;return this},appendChild:function(b){if(b&&this._nodes.length>0)if(b.constructor===this.constructor){var a=this._nodes[0];b._each(function(b){a.appendChild(b)})}else this._nodes[0].appendChild(b);return this},insertBefore:function(b,a){if(b&&this._nodes.length>0){a&&a.constructor===this.constructor&&(a=a._nodes[0]);if(!a||a.parentNode!==this._nodes[0])return this.appendChild(b);
if(b.constructor===this.constructor){var d=this._nodes[0];b._each(function(b){d.insertBefore(b,a)},null,true)}else this._nodes[0].insertBefore(b,a)}return this},insertInto:function(b){var a;if(b&&this.count()>0){b.constructor===this.constructor&&(b=b._nodes[0]);if(this.count()===1)b.appendChild(this._nodes[0]);else{a=document.createDocumentFragment();this._each(function(b){a.appendChild(b)},null,true);h.support.filters!==true&&b.appendChild(a)}}return this},remove:function(){this.fireEvent("remove");
this._each(function(b){b.parentNode&&b.parentNode.removeChild(b)});return this},destroy:function(){this.remove();this.fireEvent("destroy");this._removeAllEvents(true);this._nodes.splice(0,this._nodes.length);return this},query:function(b,f){var d=[];this._nodes.length>0&&this._each(function(i){i=a.getElement(b,puredom.extend({},f||{},{within:i}));a.isArray(i)&&i.length>0&&(d=d.concat(i))});return new a.NodeSelection(d)},clone:function(b,f){var d=[];f===true&&(f=this.parent());this._each(function(a){d.push(a.cloneNode(b!==
false))});d=new a.NodeSelection(d);f&&f.appendChild(d);d._each(h.removeNodeUID);b!==false&&d.query("*")._each(h.removeNodeUID);return d},count:function(){return this._nodes.length},exists:function(){return this.count()>0},next:function(){for(var b=this._nodes[0]&&this._nodes[0].nextSibling;b&&b.nodeType===3;)b=b.nextSibling;return new a.NodeSelection(b&&[b]||null)},prev:function(){for(var b=this._nodes[0]&&this._nodes[0].previousSibling;b&&b.nodeType===3;)b=b.previousSibling;return new a.NodeSelection(b&&
[b]||null)},previous:function(){return this.prev.apply(this,arguments)},firstChild:function(){return this.children().first()},lastChild:function(){return this.children().last()},nthChild:function(b){return this.children().index(b)},first:function(b){return new a.NodeSelection(this._nodes.slice(0,b||1))},last:function(b){return new a.NodeSelection(this._nodes.slice(this._nodes.length-(b||1)))},index:function(b,f){return new a.NodeSelection(a.typeOf(b)==="number"&&this._nodes.slice(b,b+(f||1))||null)},
siblings:function(){var b=new a.NodeSelection;this._each(function(a){for(var d=a;d=d.previousSibling;)d.nodeName!=="#text"&&(d.nodeName!=="#comment"&&d.nodeType!==3)&&b._nodes.push(d);for(d=a;d=d.nextSibling;)d.nodeName!=="#text"&&(d.nodeName!=="#comment"&&d.nodeType!==3)&&b._nodes.push(d)});return b},parent:function(){var b=[],f;this._each(function(a){(f=a.parentNode)&&(b.indexOf(f)<0&&f.nodeType!==11)&&b.push(f)});return new a.NodeSelection(b)},children:function(){var b=[],f,d;if(this._nodes.length>
0)for(f=0;f<this._nodes.length;f++)if(this._nodes[f].childNodes)for(d=0;d<this._nodes[f].childNodes.length;d++)this._nodes[f].childNodes[d].nodeType!==3&&(this._nodes[f].childNodes[d].nodeName!=="#text"&&this._nodes[f].childNodes[d].nodeName!=="#comment")&&b.push(this._nodes[f].childNodes[d]);return new a.NodeSelection(b)},submit:function(){this._each(function(b){var f=a.fireEvent({type:"submit",target:b});f.rval!==false&&f.returnValue!==false&&f.preventDefault!==true&&b.submit&&b.submit()})},selection:function(b,
f){var d=this._nodes[0],i,c;if(b&&typeof b!=="number"&&b.start){f=b.end;b=b.start}if(typeof b==="number"){b<0&&(b=0);c=d.value.length;f>c&&(f=c);b>f?b=f:f<b&&(f=b);if(window.getSelection){d.selectionStart=b;d.selectionEnd=f}else if(d.selectionEnd||d.selectionEnd===0){d.selectionStart=b;d.selectionEnd=f}else if(d.createTextRange){d=d.createTextRange();d.collapse(true);d.moveStart("character",b);d.moveEnd("character",f);d.select()}}else{if(window.getSelection){i=typeof d.value==="string"?d.value:d.innerHTML;
c=window.getSelection();return{start:d.selectionStart+0,end:d.selectionEnd+0,text:i.substring(c.start,c.end)}}if(document.selection){c=document.selection.createRange();i=document.body.createTextRange();i.moveToElementText(d);i.setEndPoint("EndToStart",c);return{start:i.text.length,end:i.text.length+c.text.length,text:c.text}}a.log("Selection retrieval is not supported in this browser.");return{start:0,end:0,text:""}}return this},template:function(b){var f,b=b||{};f=function(b){var b=b.split("|"),
a;b.splice(0,1);for(a=b.length;a--;)b[a]==="htmlEntities"&&b.splice(a,1);return b};this.query("[data-tpl-id]").each(function(d){var i=d.nodeName(),c=d.attr("data-tpl-id"),e=c,h;h=f(c);c=c.split("|")[0];e=puredom.delve(b,c);if(e!==null&&e!==void 0){if(typeof e==="date"||e.constructor===Date)e=e.toLocaleString();if(c=d.attr("data-tpl-prop"))d.prop(c,a.text.filter(e,h.join("|")));else switch(i){case "select":case "input":case "textarea":case "meter":case "progress":d.value(e);break;case "img":case "video":case "audio":case "iframe":h.splice(0,
0,"htmlEntities");e=a.text.filter(e,h.join("|"));d.attr("src",e);break;default:h.splice(0,0,"htmlEntities");e=a.text.filter(e,h.join("|"));d.html(e)}}});b=null;return this}});a.NodeSelection.prototype.on=a.NodeSelection.prototype.addEvent;a.NodeSelection.prototype.animateCss=a.NodeSelection.prototype.animateCSS;h.incrementAnimationCount=function(b){b.setAttribute("data-puredom-animation-count",h.getAnimationCount(b)+1+"");a.addClass(b,"_puredom_animating")};h.decrementAnimationCount=function(b){var f=
Math.max(0,h.getAnimationCount(b));if(f>1)b.setAttribute("data-puredom-animation-count",f-1+"");else{b.setAttribute("data-puredom-animation-count","");b.removeAttribute&&b.removeAttribute("data-puredom-animation-count");a.removeClass(b,"_puredom_animating")}};h.getAnimationCount=function(b){return parseInt(b.getAttribute("data-puredom-animation-count"),10)||0};h.unload=function(){h.wrappedEventListener.reset();a.getElement.clearCache();h._nodeToIdList={};setTimeout(function(){window.puredom=h=l=m=
null},10)};a.el=function(b,f){var d,i;if(b){i=a.typeOf(b);if(i==="array"){d=[];for(var c=0;c<b.length;c++)Array.prototype.splice.apply(d,[0,0].concat(a.el(b[c])._nodes))}if(b.constructor===a.NodeSelection){f===true&&console.log("query is already a NodeSelection",b.constructor+"",b.constructor.name);return b}if(i==="string"&&b.charAt(0)==="<"||i==="object"&&!b.nodeName&&b!==window){f===true&&console.log("query is an HTML fragment",b,i);d=a.createElement.apply(a,arguments)}else if(i==="string"){f===
true&&console.log("query is a CSS selector",b,i);d=a.getElement(b,arguments[1])}else if(b.nodeName||b===window){f===true&&console.log("query is an HTML element",b,i);d=b}}return new a.NodeSelection(d)};a.node=function(b){return new a.NodeSelection(h.idToNode(b))};var k,q,o={},y=false,A=/^((?:[a-z][a-z0-9\_\-]*)|\*)?/gi,w=/^\s*(.*?)\s*$/gm,s;s=[{title:"ID selector {#id}",regex:/^#[_a-zA-Z0-9-]*/gm,filter:function(b,a,d){return[(d.searchBaseNode&&d.searchBaseNode.getElementById?d.searchBaseNode:document).getElementById(b[0].substring(1))]}},
{title:"Class selector {.className}",regex:/^\.([^#.:\[<>\{+\|\s]+)/gim,filter:function(b,a){var d,i,c=" "+b[1]+" ";for(d=a.length;d--;){i=a[d]&&a[d].className;(!i||(" "+i+" ").indexOf(c)===-1)&&a.splice(d,1)}}},{title:"Attribute selector {[name=value] & variants}",regex:/^\[([^\^\$\~=]+)(?:([\^\$\~=]+)(['"]?)([^\]]*))?\3\]/g,filter:function(b,f){var d,i,c,e,h,k,g,o;if(b&&b[1]){d=b[1];c=i=void 0;if(b[2]&&b[4]){i=b[2];c=b[4]||""}for(k=f.length;k--;){g=d==="checked"?c==="true"||c==="false"?f[k].checked?
"true":"false":f[k].checked?"checked":null:d==="selected"?c==="true"||c==="false"?f[k].selected?"true":"false":f[k].selected?"selected":null:f[k]&&f[k].getAttribute(d+"");e=a.typeOf(g)==="string";h=g&&g.length>0;c&&(o=e?g.indexOf(c):-1);switch(i||""){case "=":e=g===c;break;case "^=":e=o===0;break;case "$=":e=h&&g.substring(g.length-c.length)===c;break;case "~=":e=o>-1;break;default:e=!c&&e}e||f.splice(k,1)}}}},{title:"Descendant selector {>}",regex:/^\s*\>\s*((?:[a-z][a-z0-9\:\_\-]*)|\*)?/gi,filter:function(b,
f,d){var i=[].concat(f),b=(b[1]||"*").toLowerCase(),c,e,h;f.splice(0,f.length);!d.isFiltered&&d.first&&a.log("Descendant selector called on an unfiltered result set.  Operating on descendants of the document.");if(!d.isFiltered||d.first)i=[d.searchBaseNode];for(d=0;d<i.length;d++){e=i[d].childNodes;for(c=0;c<e.length;c++){h=(e[c].nodeName+"").toLowerCase();(h===b||b==="*"&&h.charAt(0)!=="#"&&(e[c].nodeType===1||e[c].nodeType===9))&&f.push(e[c])}}}},{title:"nth-child aliases, like :first-child",regex:/^\:(first|last|only)\-(child|of\-type)/gm,
filter:function(b,f,d){var c={"first-child":":nth-child(0n+1)","first-of-type":":nth-of-type(0n+1)","last-child":":nth-last-child(0n+1)","last-of-type":":nth-last-of-type(0n+1)"},e,h;for(e=s.length;e--;)if(s[e].isNthChildSelector===true){h=s[e];break}if(c.hasOwnProperty(b[1]+"-"+b[2])&&h){b=c[b[1]+"-"+b[2]];h.regex.lastIndex=0;b=h.regex.exec(b);return h.filter(b,f,d)}a.log('Unknown nth-child alias "'+b[1]+"-"+b[2]+'"')}},{isNthChildSelector:true,title:"nth-child selector {:nth-child(n+2) & variants}",
regex:/^\:(nth(?:\-last)?(?:\-of\-type|\-child))\((?:(\-?[0-9]*n(?:[+-][0-9]+)?)|([0-9]+)|([a-z]+))\)/gm,filter:function(b,f){var d,c,e,h,k,g,o,j,q,l=b[1].indexOf("-of-type")!==-1;e={odd:[2,1],even:[2]};d=f.splice(0,f.length);b[1].indexOf("-last")!==-1&&d.reverse();if(b[2]){c=b[2].split("n");c[0].replace("-","").length===0&&(c[0]=c[0]+"1");j=Math.round(c[0].replace("+",""))||0;q=Math.round(c[1].replace("+",""))||0}else if(b[3]){j=0;q=Math.round(b[3])||0}else if(b[4]){c=b[4].toLowerCase();if(e.hasOwnProperty(c)){j=
e[c][0]||0;q=e[c][1]||0}else a.log('Unknown named nth-child expression "'+r[4]+'"')}if(!(j+q<=0)){j===q&&(q=0);for(c=0;c<d.length;c++){children=(d[c].parentNode||{}).childNodes;k=(d[c].nodeName+"").toLowerCase();isMatch=false;if(children)for(e=o=0;e<children.length;e++){g=children[e];if(h=l?(g.nodeName+"").toLowerCase()===k:(g.nodeName+"").substring(0,1)!=="#"||g.nodeType===1||g.nodeType===9){o=o+1;if(g===d[c])if(isMatch=j>0?o%j-q===0:o===q)break}}isMatch&&f.push(d[c])}}}},{title:"within_internal selector { }",
regex:/^\s+((?:[a-z][a-z0-9\:\_\-]*)|\*)?/gi,filter:function(b,f){var d=[].concat(f),c=b[1]||"*",e;f.splice(0,f.length);for(e=0;e<d.length;e++)Array.prototype.splice.apply(f,[f.length-1,0].concat(a.toArray(d[e].getElementsByTagName(c))))}}];q=function(b){b.lastIndex=0};k=function(b,f){var d=document&&document.documentElement||document,c,e,g=b,j,l,m,n,p=0,t=false;n=!h.support.querySelectorAll;var v=Date.now(),b=(b+"").replace(w,"$1"),f=puredom.extend({},f||{});f.logging===true&&(t=true);if(y&&f.useCache===
true&&o[b])return o[b];if(f.within)d=f.within;d&&(d.length&&!d.nodeName&&d.indexOf&&d[0])&&(d=d[0]);if(b.indexOf(",")>-1){b=b.split(",");c=[];for(m=b.length;m--;){b[m]=b[m].replace(w,"$1");if(b[m].length>0)if(d=k(b[m],puredom.extend({},f,{logging:false,internalLogging:t,internal:true})))for(e=0;e<d.length;e++)c.indexOf(d[e])===-1&&c.push(d[e])}t&&a.log("query=",g,", result=",node);v=Date.now()-v;v>100&&a.log('Slow Selector Warning: "'+g+'" took '+v+"ms to complete.");return c}e=b.match(A);e=(e&&e[0]||
"").toLowerCase();m=b=b.substring(e.length);g.charAt(0)===">"&&(n=true);if(m.match(/^#[^\s\[\]\(\)\:\*\.\,<>#]+$/gim)){c=[(d.getElementById?d:document).getElementById(m.substring(1))];n=false}else if(h.support.querySelectorAll&&n!==true){j=g.replace(/(\[[^\[\]= ]+=)([^\[\]"']+)(\])/gim,'$1"$2"$3');try{c=a.toArray(d.querySelectorAll(j)||[])}catch(x){console.log("Native querySelectorAll failed for selector: ",j,", error:",x.message);c=[];n=true}}if(n){if(b.substring(0,1)==="#")c=[];else if((!e||e===
"*")&&document.all&&!window.opera&&(d===document||d===document.documentElement)){c=a.toArray(d.all||document.all);l=false}else{c=a.toArray(d.getElementsByTagName(e||"*"));l=true}for(j={searchBaseNode:d,negated:false,first:true,isFiltered:l||!!(e&&e!=="*")};m.length>0;){p=p+1;n=false;for(e=0;e<s.length;e++){q(s[e].regex);if(d=s[e].regex.exec(m)){n=true;t&&a.log((s[e].title||s[e].regex)+' ==>> matched:"'+m.substring(0,d[0].length)+'" ==>> remaining:"'+m.substring(d[0].length)+'" ||debug>> (submatches:'+
d.slice(1).join(",")+")");(l=s[e].filter(d,c,j))&&a.isArray(l)&&(c=l);m=m.substring(d[0].length);j.first=false;j.isFiltered=true}if(m.length===0)break}if(!n)throw Error("puredom.getElement() :: Unknown CSS selector near: "+m.substring(0,20),"puredom.js",1775);}}if(f.includeInvisibles!==true)for(e=c.length;e--;)c[e]&&(c[e].nodeName+"").charAt(0)==="#"&&c.splice(e,1);t&&a.log("query=",g,", result=",c);y&&f.cache===true&&(o[b]=c);if(f.internal!==true&&t===true){v=Date.now()-v;v>10&&a.log('Slow Selector Warning: "'+
g+'" took '+v+"ms to complete. "+p+" parse iterations.")}return c};k.enableCache=function(b){(y=b!==false)||(o={})};k.disableCache=function(){y=false;o={}};k.clearCache=function(){o={}};k._normalizeSelectorFilter=function(b){arguments.length===2&&(b={regex:arguments[0],filter:arguments[1]});return b&&b.regex&&b.filter?b:false};k.addSelectorFilter=function(b){if(b=k._normalizeSelectorFilter.apply(k,arguments)){s.push(b);return true}return false};k.removeSelectorFilter=function(b){var a,d,c;if(b=k._normalizeSelectorFilter.apply(k,
arguments))for(a=s.length;a--;){c=true;for(d in s[a])if(s[a].hasOwnProperty(d)&&s[a][d]!==b[d]){c=false;break}if(c){s.splice(a,1);break}}return c===true};k.selectorStats=function(){return"disabled"};a.getElement=k;a.DOMEvent=function(){};window.wrappedEventListener=h.wrappedEventListener={list:[],none:{},summary:function(){for(var b=0;b<this.list.length;b++)a.log(h.idToNode(this.list[b].target),".on",this.list[b].type," -> ",this.list[b].handler.displayName||this.list[b].handler.name)},reset:function(b){var f;
if(b===true)for(b=this.list.length;b--;){f=this.list[b];this.list[b]=this.none;a.removeEvent(h.idToNode(f.target),f.type,f.wrappedHandler);this.unsetRefs(f);window.killCount=(window.killCount||0)+1}this.list.splice(0,this.list.length)},destroyObjHandlers:function(b){var f,d,c=h.nodeToId(b);for(f=this.list.length;f--;){d=this.list[f];if(d.target===c){this.unsetRefs(d);this.list.splice(f,1);a.removeEvent(b,d.type,d.wrappedHandler);window.killCount=(window.killCount||0)+1}}},get:function(b,a,d,c){var e,
g,d=h.nodeToId(d);for(e=this.list.length;e--;){g=this.list[e];if(g.target===d&&g.handler===a&&g.type===b){a=g.wrappedHandler;if(c===true){this.list.splice(e,1);window.killCount=(window.killCount||0)+1;this.unsetRefs(g)}break}}return a},unsetRefs:function(b){b.wrappedHandler.type=null;b.wrappedHandler.handler=null;b.wrappedHandler.target=null},internalFireEvent:function(b){var a=h.nodeToId(b.target),d=b.type.replace(/^on/gm,""),c,e;for(c=this.list.length;c--;){e=this.list[c];if(e.target===a&&e.type===
d){e=e.handler.call(b.target,b);if(e===false)break}}},create:function(b,f,d){d={type:b,target:h.nodeToId(d),handler:f,wrappedHandler:function(b){var d=arguments.callee.handler,f=(arguments.callee.type||b.type).toLowerCase().replace(/^on/,""),c=this!==window?this:h&&h.idToNode(arguments.callee.target),e,g,k={isInSelf:false,doPreventDefault:false,doCancelBubble:false,doStopPropagation:false,e:b||window.event,ret:null,end:function(){b=e=k=d=f=c=k.end=null;return this.ret}};(!h||!h.idToNode)&&a.log("target:<"+
b.target.nodeName+' class="'+b.target.className+'" id="'+b.target.id+'"> , type:'+f+"/"+b.type);b=k.e;e=a.extend(new a.DOMEvent,{which:b.which,type:f,target:b.target||b.srcElement||c||document.body,relatedTarget:b.relatedTarget||(f==="mouseout"?b.toElement:b.fromElement),preventDefault:function(){k.doPreventDefault=true},stopPropagation:function(){k.doStopPropagation=true;k.doCancelBubble=true},cancel:function(){e.preventDefault();e.stopPropagation();return e.returnValue=false},returnValue:true,originalEvent:b,
timeStamp:b.timeStamp||Date.now()});e.cancelBubble=e.stopPropagation;e.stop=e.prevent=e.cancel;for(g in b)!e.hasOwnProperty(g)&&(typeof b[g]!=="function"&&g!==g.toUpperCase())&&(e[g]=b[g]);e.target||a.log("Event target doesn't exist for type \""+e.type+'": ',e.target,", srcElement=",b.srcElement);if(b.type==="touchend"&&h._lastTouchPos){e.pageX=h._lastTouchPos.pageX;e.pageY=h._lastTouchPos.pageY}else if(b.touches&&b.touches[0]){e.pageX=b.touches[0].pageX;e.pageY=b.touches[0].pageY;h._lastTouchPos=
{pageX:e.pageX,pageY:e.pageY}}else if(b.pageX||b.pageX===0||b.clientX||b.clientX===0){e.pageX=b.pageX||b.clientX+document.body.offsetLeft;e.pageY=b.pageY||b.clientY+document.body.offsetTop}if(f.indexOf("key")>-1||b.keyCode||b.charCode){e.keyCode=b.keyCode||b.which;e.charCode=b.keyCode||b.charCode||b.which;e.which=b.which}if(f.indexOf("mouse")>-1||f.indexOf("click")>-1||b.button!==null&&b.button!==void 0)e.button=b.button||b.which;if(e.target&&e.target.nodeType===3&&c.nodeType!==3)e.target=e.target.parentNode;
k.searchNode=e.relatedTarget||e.target;do if(k.searchNode===c){k.isInSelf=true;break}while(k.searchNode&&(k.searchNode=k.searchNode.parentNode)&&k.searchNode!==document);if(f!=="mouseover"&&f!=="mouseout"||!k.isInSelf){if(d&&d.call)k.handlerResponse=d.call(c,e);e.returnValue=k.handlerResponse!==false&&e.returnValue!==false;if(k.doPreventDefault){e.returnValue=b.returnValue=false;b.preventDefault&&b.preventDefault()}if(k.doCancelBubble||k.doStopPropagation||e.cancelBubble===true){b.stopPropagation&&
b.stopPropagation();if(b.cancelBubble){if(b.cancelBubble.call)try{b.cancelBubble()}catch(o){}}else try{b.cancelBubble=true}catch(j){}}k.ret=e.returnValue}else k.ret=true;return k.end()}};d.wrappedHandler.displayName="wrappedEventHandler_"+b;d.wrappedHandler.handler=f;d.wrappedHandler.type=b;d.wrappedHandler.target=d.target;this.list.push(d);d=b=f=d=null;return this.list[this.list.length-1].wrappedHandler}};h.getSubjectDescription=function(b){return(b.nodeName?a.el(b)+"":b.constructor&&b.constructor.name||
b.name||b)+""};a.eventTypeMap={};h.support.webkitMultitouch&&a.extend(a.eventTypeMap,{mousedown:"touchstart",mousemove:"touchmove",mouseup:"touchend"});a.addEvent=function(b,f,d,c){var e;if(b){a.typeOf(f)==="string"&&f.indexOf(",")>-1&&(f=f.replace(/\s/gm,"").split(","));if(a.isArray(f)){for(c=0;c<f.length;c++)a.addEvent(b,f[c],d);return true}e=f=(f+"").toLowerCase().replace(/^\s*(on)?(.*?)\s*$/gim,"$2");if(typeof f!=="string"||!d||!d.call)a.log("Attempted to add event with invalid type or handler:",
{type:f,handler:d+"",subject:h.getSubjectDescription(b),useCapture:c===true});else{a.eventTypeMap.hasOwnProperty(f)&&(f=a.eventTypeMap[f]);d=h.wrappedEventListener.create(e,d,b);if(b.attachEvent)b.attachEvent("on"+f,d);else if(b.addEventListener){b.addEventListener(f,d,c===true);window._eventCount=(window._eventCount||0)+1}}}};a.removeEvent=function(b,f,d,c){var e;if(b){a.typeOf(f)==="string"&&f.indexOf(",")>-1&&(f=f.replace(/\s/gm,"").split(","));if(a.isArray(f)){for(e=0;e<f.length;e++)a.removeEvent(b,
f[e],d,c);return true}e=f=(f+"").toLowerCase().replace(/^\s*(on)?(.*?)\s*$/gim,"$2");if(typeof f!=="string"||!d||!d.call)a.log("Attempted to remove event with invalid type or handler:",{type:f,handler:d+"",subject:h.getSubjectDescription(b),useCapture:c===true});else{a.eventTypeMap.hasOwnProperty(f)&&(f=a.eventTypeMap[f]);d=h.wrappedEventListener.get(e,d,b,true);if(b.detachEvent)b.detachEvent("on"+f,d);else if(b.removeEventListener)try{b.removeEventListener(f,d,c===true);window._eventCount=(window._eventCount||
0)-1}catch(k){}}}};a.cancelEvent=function(b){if(b=b||window.event){b.preventDefault&&b.preventDefault();b.stopPropagation&&b.stopPropagation();try{b.cancelBubble=true}catch(a){}b.returnValue=false}return false};a.fireEvent=function(b){var c,d,e,k,g,b=b||{};if(document.createEventObject){b=a.extend({},b);b.type="on"+b.type.toLowerCase().replace(/^on/,"");try{c=document.createEventObject()}catch(o){g=true}if(!g){for(e in b)if(b.hasOwnProperty(e))try{c[e]=b[e]}catch(j){}try{d=b.target.fireEvent(b.type,
c);k=c.preventDefault===true}catch(q){g=true}}g&&h.wrappedEventListener.internalFireEvent&&h.wrappedEventListener.internalFireEvent(b)}else{c=document.createEvent("HTMLEvents");c.initEvent(b.type.toLowerCase().replace(/^on/,""),true,true);for(e in b)if(b.hasOwnProperty(e))try{c[e]=b[e]}catch(l){}d=!b.target.dispatchEvent(c);k=c.preventDefault===true}return{evt:c,preventDefault:k,rval:d}};h._nodeToIdIndex=0;h._nodeToIdList={};window._nodeToIdList=h._nodeToIdList;h.nodeToId=function(b){var c;if(b===
window)return"_td_autoid_window";if(b===document)return"_td_autoid_document";if(b===document.body)return"_td_autoid_documentbody";if((c=/\s_td_autoid_([0-9]+)\s/gm.exec(" "+b.className+" "))&&c[1])c=c[1];else{h._nodeToIdIndex=h._nodeToIdIndex+1;c=h._nodeToIdIndex+"";a.addClass(b,"_td_autoid_"+c)}h.ensureNodeIdListing(b,c);return c};h.idToNode=function(b){var c;c=h._nodeToIdList[b+""];var d;if(b==="_td_autoid_window")return window;if(b==="_td_autoid_document")return document;if(b==="_td_autoid_documentbody")return document.body;
if(c){d=a.getElement(c);/\s_td_autoid_[0-9]+\s/gm.exec(" "+d.className+" ")||(d=null)}if(!d)(d=(c=a.getElement("._td_autoid_"+b))&&c[0])&&h.ensureNodeIdListing(d,b);return d||false};h.ensureNodeIdListing=function(b,a){var d;if(b.getAttribute){d=b.getAttribute("id");if(!d){d="_td_autoid_"+a;b.setAttribute("id",d)}h._nodeToIdList[a]="#"+d}};h.removeNodeUID=function(b){var a=b.getAttribute("id");a&&a.match(/^_td_autoid_[0-9]+$/g)&&(b.removeAttribute?b.removeAttribute("id"):b.setAttribute("id",""));if(b.className)b.className=
b.className.replace(/(^|\b)_td_autoid_[0-9]+(\b|$)/gim,"")};var x=void 0,v={manualFramerate:11};window.mozRequestAnimationFrame?x="moz":window.webkitRequestAnimationFrame&&(x="webkit");v.nativeSupport=!!x;if(v.nativeSupport){v.getTimer=function(b){return window[x+"RequestAnimationFrame"](b)};v.cancelTimer=function(b){window[x+"CancelRequestAnimationFrame"](b)};v.getStartTime=function(){return window[x+"AnimationStartTime"]||(new Date).getTime()}}else{v.getTimer=function(b){return setTimeout(function(){b((new Date).getTime());
b=null},v.manualFramerate)};v.cancelTimer=function(b){clearTimeout(b)};v.getStartTime=function(){return(new Date).getTime()}}a.animationFrame=v;a.setOpacity=function(b,a){a<=1&&a>0&&(a=a*100);a=Math.round(a);if(a<100){b.style.opacity=parseFloat(a/100).toFixed(2);b.style.filter="alpha(opacity="+a+")"}else{b.style.opacity=null;b.style.filter=null}};a.applyMsFilter=function(b,c,d){var e,k="",g=h.support.filterProperty==="MsFilter"?'"':"",o,j,q,c=c.charAt(0).toUpperCase()+c.substring(1);if(typeof d===
"string"){k=d;d={};j=k.replace(/\s*(,|=)\s*      /gm,"$1").split(",");for(o=0;o<j.length;o++){q=j[o].indexOf("=");d[j[o].substring(0,q)]=j[o].substring(q+1)}}else{for(o in d)d.hasOwnProperty(o)&&(k=k+(", "+o+"="+d[o]));k=k.replace(",","")}try{e=b.filters&&b.filters.item&&(b.filters.item("DXImageTransform.Microsoft."+c)||b.filters.item(c))}catch(l){}if(e){for(o in d)d.hasOwnProperty(o)&&o!=="enabled"&&(e[o]=d[o]);e.enabled=d.enabled?1:0}else{d=b.style.MsFilter||b.style.filter||"";(d=d+(" "+(a.nodeStyle(b,
"MsFilter")||a.nodeStyle(b,"filter")||"")))&&(d=d.replace(RegExp('(^|s|))"?((progid:)?DXImageTransform.Microsoft.)?'+c+'s*?(.*?)"?s*?',"gim"),"$1")+" ");b.style[h.support.filterProperty]=d+g+"progid:DXImageTransform.Microsoft."+c+"("+k+")"+g}if(!b.style.zoom)b.style.zoom=1};a.applyCss=function(b,c){var d,e,k,o,q,c=c||{};for(d in c)if(c.hasOwnProperty(d))try{e=a.getStyleAsCSS(d);e=e.replace(/^\-(moz|webkit|ms|o|vendor)\-/gim,g+"-");e=a.getStyleAsProperty(e);if(e==="opacity"&&h.support.filters){q=Math.round(parseFloat(c[d])*
100);q<100?a.applyMsFilter(b,"alpha",{enabled:true,opacity:q}):a.applyMsFilter(b,"alpha",{enabled:false})}else if(e==="--box-shadow"&&h.support.filters){k=(k=c[d].match(/\b(\#[0-9af]{3}[0-9af]{3}?|rgba?\([0-9\,\s]+\))\b/gim))&&k[0]||"";o=(" "+c[d]+" ").replace(k,"").replace(/\s+/m," ").split(" ").slice(1,4);a.applyMsFilter(b,"glow",{Color:k,Strength:Math.round(o[3].replace(/[^0-9\-\.]/gim,""))})}else{b.style[e]=c[d];if(e==="boxShadow"||e==="textShadow"||e==="borderRadius")j&&(b.style[j+e]=c[d])}}catch(l){}};
a.getStyleAsProperty=function(b){return a.typeOf(b)==="string"&&b.replace(/\-[a-z0-9]/gim,function(b){return b.charAt(1).toUpperCase()})||null};a.getStyleAsCSS=function(b){return a.typeOf(b)==="string"&&b.replace(/\-*[A-Z]/gm,"-$0").toLowerCase()||null};a.getCssTransitions=function(b){var c={},d={properties:"-vendor-transition-property",durations:"-vendor-transition-duration",timingFunctions:"-vendor-transition-timing-function"},e,k;for(e in d)d.hasOwnProperty(e)&&(d[e]=(a.nodeStyle(b,d[e])||"").replace(/\s/,
"").split(","));for(b=0;b<d.properties.length;b++)if(d.properties[b]&&d.properties[b]!=="null"&&!(d.properties[b]==="all"&&d.durations[b].match(/^[0\.ms]*$/))){e=d.durations[b]||d.durations[d.durations.length-1];k=parseFloat(e.replace(/[^\-0-9\.]/gim,""))||0;e.match(/ms$/i)||(k=k*1E3);c[a.getStyleAsProperty(d.properties[b])]={duration:k,timingFunction:d.timingFunctions[b]||d.timingFunctions[d.timingFunctions.length-1]||"ease"}}return c};a.setCssTransitions=function(b,c){var d={"-vendor-transition-property":[],
"-vendor-transition-duration":[],"-vendor-transition-timing-function":[]},e;for(e in c)if(c.hasOwnProperty(e)&&c[e]){d["-vendor-transition-property"].push(e.toLowerCase());d["-vendor-transition-duration"].push((c[e].duration/1E3).toFixed(3)+"s");d["-vendor-transition-timing-function"].push(c[e].timingFunction||"ease")}for(e in d)d.hasOwnProperty(e)&&(d[e]=d[e].join(", "));a.applyCss(b,d)};a.updateCssTransitions=function(b,c){var d,e;if(c){d=a.getCssTransitions(b);for(e in c)c.hasOwnProperty(e)&&(c[e]?
d[e]=c[e]:delete d[e]);a.setCssTransitions(b,d)}};a.addClass=function(b,c){var d,e;if(c){a.isArray(c)||(c=[c]);d=b.className||"";if(d.length>0){d=" "+d+" ";for(e=0;e<c.length;e++)for(;d.indexOf(" "+c[e]+" ")>-1;)d=d.replace(" "+c[e]+" "," ");d=d.substring(1)}b.className=(d+c.join(" ")).replace(/\s+/gim," ")}};a.removeClass=function(b,c){var d,e;if(c){a.isArray(c)||(c=[c]);d=b.className||"";if(d.length>0){d=" "+d+" ";for(e=0;e<c.length;e++)for(;d.indexOf(" "+c[e]+" ")>-1;)d=d.replace(" "+c[e]+" ",
" ");d=d.substring(1)}b.className=d.replace(/\s+/gim," ")}};a.nodeStyle=function(b,a){var d=(a+"").replace(/[A-Z]/g,"-$0").toLowerCase(),c,e,d=d.replace(/^\-(moz|webkit|ms|o|vendor)\-/gim,g+"-");c=d.replace(/\-[a-z]/gim,function(b){return b.substring(1).toUpperCase()});if(d==="opacity"&&h.support.filters)return b.filters.alpha&&b.filters.alpha.enabled!==false&&Math.round(b.filters.alpha.opacity)/100;if(b.style&&b.style[c])e=b.style[c]||"";else if(b.currentStyle&&b.currentStyle[c])e=b.currentStyle[c]||
b.currentStyle[d]||"";else if(document.defaultView&&document.defaultView.getComputedStyle)e=(e=document.defaultView.getComputedStyle(b,null))&&(e.getPropertyValue(d)||e.getPropertyValue(c))||"";else if(window.getComputedStyle)e=(e=window.getComputedStyle(b,null))&&(e.getPropertyValue(d)||e.getPropertyValue(c))||"";return e};a.htmlEntities=function(b,c){var d=["htmlEntities"];c===true&&d.push("stripTags");return a.text.filter(b,d)};a.log=function(){var b,a,c;if(window.console&&window.console.log)try{window.console.log.apply(window.console,
arguments)}catch(e){c=[];b="args[0]";for(a=1;a<arguments.length;a++){c.push(arguments[a]);b=b+(",args["+a+"]")}eval("window.console.log("+b+")")}};a.addNodeSelectionPlugin=function(b,c){a.NodeSelection.prototype.hasOwnProperty(b)||(a.NodeSelection.prototype[b]=function(){var b=c.apply(this,arguments);if(b===null||b===void 0)return this})};a.init=function(){if(!c){c=true;a.forEach(h.oninit,function(b){b.call(a,a)});a.fireEvent({target:document.body,type:"puredomready",puredom:a})}};a.addEvent(document,
"DOMContentLoaded",a.init);a.addEvent(window,"load",a.init);a.addEvent(window,"unload",h.unload);if(window._previousPureDom){for(var z in window._previousPureDom)window._previousPureDom.hasOwnProperty(z)&&(a[z]=window._previousPureDom[z]);window._previousPureDom=null;try{delete window._previousPureDom}catch(B){}}h.puredom=function(b){if(a.typeOf(b)==="function"){c===true?b.call(a,a):h.oninit.push(b);return a}return a.el.apply(a,arguments)};a.extend(a,e);a.toString=function(){return"function puredom(){}"};
window.puredom=a})();window.puredom=window.puredom||{};
(function(){var a,e=function(){return e.filter.apply(this,arguments)},c=/[&<>"]/gim,g=/(^|\s)[a-z]/gim,j=/^[a-z]/gim,l=/\r?\n/g,n=/[^0-9.\-]/gim;e.filter=function(a,c){var g,h,j,l,m;puredom.typeOf(c)!=="array"&&(c=((c||"")+"").split("|"));if(arguments.length>2)for(g=2;g<arguments.length;g++)puredom.typeOf(arguments[g])==="array"?c=c.concat(arguments[g]):c.push(arguments[g]);for(g=0;g<c.length;g++){h=c[g];l=[a];j=h.indexOf(":");if(j>-1){h=h.substring(0,j);l=l.concat(c[g].substring(j+1).split(","))}for(m in e)if((m+
"").toLowerCase()===h.toLowerCase()){a=e[m].apply(e,l);break}}return a};e.escape=function(a){return encodeURIComponent(a)};e.unescape=function(a){return decodeURIComponent(a)};e.htmlEntities=function(a){var e={"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"};return(a+"").replace(c,function(a){return e[a]})};e.ucWords=function(a){return(a+"").toLowerCase().replace(g,function(a){return a.toUpperCase()})};e.ucFirst=function(a){return(a+"").toLowerCase().replace(j,function(a){return a.toUpperCase()})};
e.nl2br=function(a){return(a+"").replace(l,"<br />")};e.numbersOnly=function(a){return(a+"").replace(n,"")};e.truncate=function(a,c,e,g){var h=false,j=a+"",a=j,c=parseInt(c,10)||80,g=g||"...";if(a.length>c){if(e===true||e==="true"||e==="byWord"){a=a.substring(0,c);j.charAt(c).match(/\s/)||(a=a.replace(/\s[^\s]*$/,""))}else a=a.substring(0,c-g.length);h=true}h&&(a=a+g);return a};e.trim=function(a){var c,e,a=a.replace(/^\s\s*/,"");c=/\s/;for(e=a.length;c.test(a.charAt(--e)););return a.slice(0,e+1)};
e["default"]=function(a,c){return(a=e.trim(a))?a:c};e.dateformat=function(a,c){var e=puredom.i18n,g=puredom.date,h;g&&g.create&&(h=g.create(a));if(!h||(h+"").indexOf("Invalid")>-1){h=new Date(a);if(!h||(h+"").indexOf("Invalid")>-1){h=new Date;h.setTime(Math.round(a))}}c&&c.indexOf("%")>-1?g&&g.format&&(a=g.format(h,c)):e&&(a=e(h,null,null,{datetype:c||"date"})||h+"");return a};a=e;var m={},h=function(){if(this.constructor!==arguments.callee&&this.constructor!==h)return new h;this.data={}};puredom.extend(h.prototype,
{defaultType:"_default",purge:function(){this.data={}},get:function(a,c,e){var g;if(arguments.length===2){e=c=a;a=null}a=(a||this.defaultType)+"";c=c+"";g=this.data.hasOwnProperty(a)&&this.data[a][c]||false;if(e){g&&e(g);return!!g}return g},set:function(a,c,e){if(arguments.length===2){e=c=a;a=null}a=(a||this.defaultType)+"";this.data[a]||(this.data[a]={});this.data[a][c+""]=e},proxySet:function(a,c,e,g){var h=this;return function(){h.set(a,c,arguments[g||0]);e&&e.apply(e,arguments)}},each:function(a){return puredom.foreach(this.data,
a)}});var p=function(a){return puredom.typeOf(a)==="string"?p.parse(a):p.stringify(a)};p.stringify=function(a){var c;try{c=JSON.stringify(a)}catch(e){puredom.log("puredom.json:: Stringify failed: "+e+" | "+a)}return c};p.parse=function(a){var c;if(typeof a==="string"&&a.length>0)try{c=JSON.parse(a)}catch(e){puredom.log("puredom.json:: Parse failed: "+e+" | "+a)}return c};p.serialize=p.stringify;p.unserialize=p.parse;a={text:a,parameterize:function(a,c){var e=[],g,h,j,l=puredom.extend({delimiter:"&",
startDelimiter:"?",assignment:"=",typeHandlers:null},c);for(g in a)if(a.hasOwnProperty(g)){h=a[g];j=this.typeOf(h);if(l.typeHandlers&&l.typeHandlers.hasOwnProperty(j))e.push(l.delimiter+encodeURIComponent(g)+"="+encodeURIComponent(l.typeHandlers[j](h)));else if(j==="array"&&l.disableArrayParams!==true)for(j=0;j<h.length;j++)e.push(l.delimiter+encodeURIComponent(g)+"[]="+encodeURIComponent(h[j]));else{switch(j){case "boolean":h=h?"true":"false";break;case "null":case "undefined":h="";break;case "object":h=
l.useJsonForObjects!==false?this.json(h):this.parameterize(h)}e.push(encodeURIComponent(g)+"="+encodeURIComponent(h))}}e=e.join(l.delimiter||"&");return e=(l.startDelimiter||"")+e},querystring:{parse:function(a){var c,e,g={};a.substring(0,1)==="?"&&(a=a.substring(1));a=a.split("&");for(c=0;c<a.length;c++)if(a[c]){e=a[c].indexOf("=");g[decodeURIComponent(a[c].substring(0,e))]=e<0?"":decodeURIComponent(a[c].substring(e+1))}return g},stringify:function(a,c){c=puredom.extend({startDelimiter:""},c||{});
return puredom.parameterize(a,c)},build:function(){return puredom.querystring.stringify.apply(puredom.querystring,arguments)}},cookies:{set:function(a,c,e,g,h,j){var l="",n="",p,h=typeof h==="string"?h:"";if(e){p=new Date;p.setTime(p.getTime()+e*864E5);l="; expires="+p.toGMTString()}m.hasOwnProperty(a)&&m[a].expires&&(l="; expires="+m[a].expires.toGMTString());n=a+"="+encodeURIComponent(c)+l+"; path=/"+h.replace(/^\//,"");typeof g==="string"&&g.length>0&&(n=n+("; domain="+g.replace(/[\;\,]/,"")));
j===true&&(n=n+"; secure");document.cookie=n;m[a]={value:c,expires:p}},get:function(a,c){if(m.hasOwnProperty(a)&&c!==true)return m[a].value;var e,g,h=document.cookie.split(";");for(g=0;g<h.length;g++){e=h[g].replace(/^\s+/gim,"");if(e.indexOf(a+"=")===0)return decodeURIComponent(e.substring(a.length+1,e.length))}return null},remove:function(a){this.set(a,"",-1);delete m[a]},purge:function(){for(var a in m)if(m.hasOwnProperty(a)){this.remove(a);delete m[a]}},read:function(){return this.get.apply(this,
arguments)},write:function(){return this.set.apply(this,arguments)}},Cache:h,json:p,xml:{parse:function(a){var c;if(window.DOMParser)c=(new window.DOMParser).parseFromString(a,"text/xml");else{c=new window.ActiveXObject("Microsoft.XMLDOM");c.async="false";c.loadXML(a)}return c}}};for(var t in a)a.hasOwnProperty(t)&&(puredom[t]=a[t]);a=null})();window.puredom=window.puredom||{};puredom.EventEmitter=function(){this._eventRegistry=[]};
puredom.EventEmitter.prototype.addEventListener=function(a,e){var c,g,a=(a+"").toLowerCase().replace(/\s+/gim,"");if(a.indexOf(",")>-1){c=a.split(",");for(g=0;g<c.length;g++)this.addEventListener(c[g],e);return this}a=a.replace(/^on/,"");this._eventRegistry.push({type:a,handler:e});return this};puredom.EventEmitter.prototype.addListener=puredom.EventEmitter.prototype.addEventListener;puredom.EventEmitter.prototype.on=puredom.EventEmitter.prototype.addEventListener;
puredom.EventEmitter.prototype.removeEventListener=function(a,e){var c,g,a=(a+"").toLowerCase().replace(/\s+/gim,"");if(a.indexOf(",")>-1){c=a.split(",");for(g=0;g<c.length;g++)this.removeEventListener(c[g],e);return this}a=a.replace(/^on/,"");for(c=this._eventRegistry.length;c--;){g=this._eventRegistry[c];if(g.type===a&&g.handler===e){this._eventRegistry.splice(c,1);break}}return this};puredom.EventEmitter.prototype.removeListener=puredom.EventEmitter.prototype.removeEventListener;
puredom.EventEmitter.prototype._fireEvent=function(a,e){var c,g,j=[],a=(a+"").toLowerCase().replace(/^on/,"");puredom.isArray(e)||(e=[e]);for(c=this._eventRegistry.length;c--;){g=this._eventRegistry[c];if(g.type===a){if(j.length===0)j.falsy=j.falsey=j.truthy=true;g=g.handler.apply(this,e);j.push(g);if(g===true)j.falsy=j.falsey=false;else if(g===false)j.truthy=false;if(g===false)break}}return j};window.puredom=window.puredom||{};
puredom.net={HttpRequest:function(a){puredom.extend(this,a)},get:function(a,e,c){return this.request(puredom.extend({url:a,type:"GET",callback:e},c||{}))},post:function(a,e,c,g){return this.request(puredom.extend({url:a,type:"POST",post:e,callback:c},g||{}))},multiLoad:function(a,e){if(!a)return false;var c=-1,g=a.length,j=[],l,n;l=function(g,h){if(g&&h){var p=a[c],t=h;if(p.process&&p.process.call){t=p.process(t);t===void 0&&(t=h)}j.push(t);e&&e(false,j,0,0);l=n=a=j=e=null}else n()};n=function(){c=
c+1;var j=a[c];(j=typeof j==="string"?{url:j}:j)?http.request(j,l):c<g?n():e(false,null,null,"No resources were available.")};n();return true},request:function(a,e){var c,g,j;if(!a.url)return false;j=this;a=a||{};c=new puredom.net.HttpRequest({url:a.url,type:a.type||(a.post?"POST":"GET"),callback:a.callback||e||function(){},post:a.post,headers:a.headers});if(a.contentTypeOverride){c.contentTypeOverride=a.contentTypeOverride;delete a.contentTypeOverride}this.createXHR(c.url,function(a){c.request=a.xhr;
c._xdrFrame=a.frame;a=null;if(c.post&&puredom.typeOf(c.post)==="object"){c.post=puredom.parameterize(c.post);if(c.post.substring(0,1)==="?")c.post=c.post.substring(1)}c.request.onreadystatechange=function(){var a;if(c.request._orig){c.request.readyState=c.request._orig.readyState;c.request.status=c.request._orig.status;c.request.responseText=c.request._orig.responseText;c.request.responseXML=c.request._orig.responseXML}if(c.request.readyState===4){c._xdrFrame&&setTimeout(function(){j._freeIframes.push(c._xdrFrame);
j=null},100);c.status=c.request.status;if(c.contentTypeOverride)a=c.contentTypeOverride.toLowerCase();else{try{a=c.request.getResponseHeader("Content-Type").toLowerCase()}catch(e){}a=a||""}c.responseText=c.request.responseText;if(a.match(/\/(json|javascript)$/gm)||a==="json"){c.responseType="json";a=c.responseJSON=null;try{a=c.responseJSON=JSON.parse(c.request.responseText.replace(/^[^\[\{]*(.*)[^\[\{]*$/g,"$1"))}catch(g){c.jsonParseError=true}}else if(a==="application/xml"||a==="xml"){c.responseType=
"xml";a=c.responseXML=c.request.responseXML}else{c.responseType="text";a=c.responseText}c.callback&&c.callback(c.request.status<300,a)}};c.request.open(c.type,c.url,c.async!==false);c.request.setRequestHeader("content-type","application/x-www-form-urlencoded");c.request.setRequestHeader("x-requested-with","XMLHttpRequest");if(c.headers)for(g in c.headers)if(c.headers.hasOwnProperty(g))try{c.request.setRequestHeader(g,c.headers[g])}catch(e){}c.request.send(c.post||null)});return c},jsonp:function(){var a=
function(){return a.get.apply(a,arguments)},e=0;a.get=function(a,g,j){var l,n,m,h;if(puredom.typeOf(g)==="function"){j&&puredom.typeOf(j)==="object"&&(h=j);j=g;h&&(g=h)}g=g||{};if(g.callback&&!j)j=g.callback;if(!g.timeout)g.timeout=10;a=a||g.url;if(!a)return false;g.params&&puredom.parameterize&&(a=a+((a.indexOf("?")>-1?"&":"?")+puredom.querystring.stringify(g.params)));e=e+1;g.callback=m="puredom_net_jsonp_"+e;window[g.callback]=function(a){var c;if(j){try{j(a)}catch(e){c=e}j=null}if(n){n.stop();
n=null}if(c)throw c;};a=a.indexOf("{!callback}")>-1?a.replace("{!callback}",m):a+((a.indexOf("?")<0?"?":"&")+encodeURIComponent(g.callbackParam||"callback")+"="+encodeURIComponent(m));if(!this._head)this._head=(h=document.getElementsByTagName("head"))&&h[0];l=puredom.el({type:"script",attributes:{src:a,async:"async",type:"text/javascript"},parent:this._head||document.body});n={id:m,stop:function(){n._timer&&clearTimeout(n._timer);window[m]=null;try{delete window[m]}catch(a){}j=null;l.attr("src","about:blank").remove();
m=n=l=null}};if(g.timeout&&g.timeout>0)n._timer=setTimeout(function(){j&&j({_requestTimedOut:true,_jsonpTimedout:true,success:false,result:false});n&&n.stop()},Math.round(g.timeout*1E3));a=g=h=null;return n};return a}(),_freeIframes:[],_xhrIndex:0,createXHR:function(a,e){var c=false,g=this,j,l,n,m,h,p;this._xhrIndex=this._xhrIndex+1;if(a)if((j=(j=/^[a-z]{3,9}\:\/\/([^\/\?#]+)/gim.exec(a))&&j[1])&&j!==location.hostname){c=true;document.domain=location.hostname.match(/[^.]+\.[^.]+$/gim)[0];for(p=0;p<
this._freeIframes.length;p++)if(this._freeIframes[p].getAttribute("data-xhr-domain")===j){l=this._freeIframes.splice(p,1)[0];break}if(l)e(g._createXHRObj(l.contentWindow,l));else{l=document.createElement("iframe");l.style.cssText="position:absolute; left:0; top:-1000px; width:1px; height:1px; border:none; overflow:hidden;";m=function(){var a,c;try{c=(a=l.contentWindow)&&a.document&&a.document.domain===document.domain&&a.document.body}catch(p){c=null}if(c&&c.innerHTML){clearInterval(h);l.onload=l.onerror=
null;e(g._createXHRObj(a,l));g=e=n=l=j=m=h=null}};l.onload=l.onerror=m;l.setAttribute("src",location.protocol+"//"+j+"/xd_receiver.html");l.setAttribute("role","presentation");l.setAttribute("tabindex","-1");l.setAttribute("data-xhr-domain",j);document.body.appendChild(l);h=setInterval(m,50)}}if(!c){n=this._createXHRObj();e(n);return n}},_createXHRObj:function(a,e){var c,a=a||window;try{c=new a.XMLHttpRequest}catch(g){try{c=new a.ActiveXObject("Msxml2.XMLHTTP")}catch(j){c=new a.ActiveXObject("Microsoft.XMLHTTP")}}return{xhr:c,
frame:e}}};window.puredom=window.puredom||{};puredom.LocalStorage=function(a,e,c){var g=this,c=c||{};this.id=a;this.adapter=null;this.data={};c.adapter&&this.setAdapter(c.adapter);!this.adapter&&c.useBest!==false&&this.useBestAdapter();if(this.adapter&&c.restore!==false)this.restore(function(){e&&e(g);g=c=null});else if(e){e(g);g=null}};puredom.LocalStorage.prototype.commitDelay=100;puredom.LocalStorage.prototype.data={};
puredom.LocalStorage.prototype.setAdapter=function(a){var e=this.constructor.adapters,c=(a+"").toLowerCase(),g=false,j=false,l;for(l in e)if(e.hasOwnProperty(l)&&(l+"").toLowerCase()===c){g=true;if(e[l].test(this)===true){j=true;this.adapterName=a;this.adapter=e[l];break}}if(!g){puredom.log('puredom.LocalStorage :: Could not find "'+a+'" adapter.');return false}if(!j){puredom.log('puredom.LocalStorage :: "'+a+'" adapter test() failed: conditions for adapter use not met.');return false}return true};
puredom.LocalStorage.prototype.getAdapter=function(){return this.adapterName};puredom.LocalStorage.prototype.useBestAdapter=function(){var a=this.constructor.adapters,e,c,g;for(g in a)if(a.hasOwnProperty(g)&&a[g].test(this)===true&&(!e||(Math.round(e.rating)||0)<(Math.round(a[g].rating)||0))){e=a[g];c=g}if(e){this.adapterName=c;this.adapter=e}else{setTimeout(function(){throw"puredom.LocalStorage :: Could not find the best adapter.";},1);return false}return true};
puredom.LocalStorage.prototype.getNamespace=function(a){var e=this,c,a=a+"";a.substring(0,1)==="."&&(a=a.substring(1));a.substring(a.length-1)==="."&&(a=a.substring(0,a.length-1));c=puredom.extend(new puredom.LocalStorage.NamespacedLocalStorage,{getAdapter:function(){return e.getAdapter()},getNamespace:this.getNamespace,getValue:function(c){return e.getValue(a+"."+c)},setValue:function(c,j){e.setValue(a+"."+c,j);return this},removeKey:function(c){e.removeKey(a+"."+c);return this},purge:function(){e.removeKey(a);
return this},getData:function(){return e.getValue(a)},restore:function(a){var c,l=this;a&&(c=function(){a(l);l=c=a=null});e.restore(c);return this},commit:function(a){var c,l=this;a&&(c=function(){a(l);l=c=a=null});e.commit(c);return this}});puredom.extend(c,{get:c.getValue,set:c.setValue,remove:c.removeKey});return c};puredom.LocalStorage.prototype.getData=function(){return this.data};puredom.LocalStorage.prototype.getValue=function(a){return puredom.delve(this.data,a)};
puredom.LocalStorage.prototype.setValue=function(a,e){var c=this.data,g=a.split("."),j;for(j=0;j<g.length-1;j++){c.hasOwnProperty(g[j])||(c[g[j]]={});c=c[g[j]]}if(e===void 0||e===null){c[g[g.length-1]]=null;delete c[g[g.length-1]]}else c[g[g.length-1]]=e;this.queueCommit();return this};puredom.LocalStorage.prototype.removeKey=function(a){this.setValue(a,void 0);return this};puredom.LocalStorage.prototype.get=puredom.LocalStorage.prototype.getValue;puredom.LocalStorage.prototype.set=puredom.LocalStorage.prototype.setValue;
puredom.LocalStorage.prototype.remove=puredom.LocalStorage.prototype.removeKey;puredom.LocalStorage.prototype.purge=function(){this.data={};this.queueCommit();return this};puredom.LocalStorage.prototype.restore=function(a){var e=this,c,g;if((c=this._adapterCall("load",function(c){e.data=g=c||{};a&&a(e);e=null}))&&!g){this.data=c;a&&a(this)}c=g=null;return this};
puredom.LocalStorage.prototype.commit=function(a){var e=this;if(this._commitTimer){clearTimeout(this._commitTimer);this._commitTimer=null}this._adapterCall("save",this.data,function(){a&&a(e);e=null});return this};puredom.LocalStorage.prototype.queueCommit=function(){var a=this;if(!this._commitTimer)this._commitTimer=setTimeout(function(){a.commit();a=null},this.commitDelay)};
puredom.LocalStorage.prototype._adapterCall=function(a,e){if(this.adapter&&this.adapter[a])return this.adapter[a].apply(this.adapter,[this].concat(puredom.toArray(arguments).slice(1)))};puredom.LocalStorage.NamespacedLocalStorage=function(){};puredom.LocalStorage.adapters={};
puredom.LocalStorage.addAdapter=function(a,e){if(e.save)if(e.load)this.adapters[a]=e;else throw'puredom.LocalStorage :: Adapter "'+a+'" attempted to register, but does not provide a load() method.';else throw'puredom.LocalStorage :: Adapter "'+a+'" attempted to register, but does not provide a save() method.';};window.puredom=window.puredom||{};
puredom.date={now:Date.now?function(){return Date.now()}:function(){return+new Date},create:function(a){if(a){a=(a+"").replace(/^([0-9]{4})\-([0-9]{2})\-([0-9]{2})T([0-9]{2})\:([0-9]{2})\:([0-9]{2})\.[0-9]{3}Z$/,"$1/$2/$3 $4:$5:$6");a=new Date(a)}else a=new Date;return a},parse:function(a,e){var c,g,j,l,n;function m(a,e){if(e===false||e===true)c=e===true;if(a||a===0)g=a;a=g;g<12&&c&&(a=a-12);var j=h.getDate();if(g===12&&c===false)(h.getHours()!==0||e===!!e)&&h.setHours(0);else{h.setHours(a);h.setDate(j)}}
var e=e||"%d/%m/%Y",h=new Date(0);n=l=j=g=c=void 0;var p={H:[/^[0-9]{1,2}/g,function(a){a=Math.round(a);m(a)}],I:[/^[0-9]{1,2}/g,function(a){a=Math.round(a);m(a)}],p:[/^[AP]M/gi,function(a){m(null,a.toLowerCase()==="pm")}],M:[/^[0-9]{1,2}/g,function(a){h.setMinutes(Math.round(a))}],a:[/^(Mon|Tue(s?)|Wed|Thu|Fri|Sat|Sun)/i,function(){}],A:[/^(Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday)/i,function(){}],d:[/^[0-9]{1,2}/g,function(a){j=Math.round(a);h.setDate(j)}],m:[/^[0-9]{1,2}/g,function(a){l=
Math.round(a)-1;h.setMonth(l)}],B:[RegExp("^("+this.months.join("|")+")","gi"),function(a){l=date._getMonthIndex(a);h.setMonth(l)}],b:[/^(Jan|Feb|Mar|Apr|May|Jun(e?)|Jul(y?)|Aug|Sep(t?)|Oct|Nov|Dec)/gi,function(a){l=date._getMonthIndex(a);h.setMonth(l)}],y:[/^[0-9]{2}/g,function(a){a=Math.round(a)+1900;a<1950&&(a=a+100);h.setFullYear(a)}],Y:[/^[0-9]{4}/g,function(a){n=Math.round(a);h.setFullYear(n)}]},t,k,q;p.l=p.I;p.e=p.d;p.P=p.p;p.h=p.b;for(t=0;t<e.length;t++)if(e.charAt(t)==="%"){k=null;a.charAt(0)===
" "&&e.charAt(t)==="%"&&(a=a.substring(1));for(q in p)if(p.hasOwnProperty(q)&&e.substring(t+1,t+1+q.length)===q){k=p[q];a=a.replace(k[0],function(a){k[1](a);return""});t=t+(k.length-1);break}}else a.charAt(0)===e.charAt(t)&&(a=a.substring(1));(l||l===0)&&h.setMonth(l);(n||n===0)&&h.setFullYear(n);return h},unformat:function(){return this.parse.apply(this,arguments)},format:function(a,e){e=e||"%d/%m/%Y";if(!a||a.constructor!==Date||!a.toDateString)return false;var c=a.toDateString();if(!c||c.toLowerCase()===
"invalid date"||c==="NaN")return false;var c=c.split(" "),g=a.getHours(),j=(g+11)%12+1,l=a.getMonth()+1,n={H:g,I:(j<10?"0":"")+j,l:j,p:g>11?"PM":"AM",P:g>11?"pm":"am",M:(a.getMinutes()<10?"0":"")+a.getMinutes(),S:(a.getSeconds()<10?"0":"")+a.getSeconds(),a:c[0],A:this.weekdays[a.getDay()],d:c[2],e:Math.round(c[2]),m:(l<10?"0":"")+l,B:this.months[Math.round(c[1])],b:c[1],h:c[1],y:c[3].substring(2),Y:c[3]};return e.replace(/%[HIlpPMSaAdemBbhyY]/gm,function(a){var c=n[a.charAt(1)+""];return c||c===0||
c===false?c:a})},_getMonthIndex:function(a){for(var a=a.substring(0,3).toLowerCase(),e=0;e<this.months.length;e++)if(this.months[e].substring(0,3).toLowerCase()===a)return e;return-1},weekdays:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),months:"January February March April May June July August September October November December".split(" ")};
puredom.LocalStorage.addAdapter("UserData",{defaultName:"db",rating:20,test:function(){return/\bMSIE\s[1-6](\.[0-9]*)?/gim.test(navigator.userAgent+"")?false:typeof document.body.addBehavior!=="undefined"},load:function(a,e){var c=this._getKey(a),c=this._getStore(c),g,j;c&&(g=c.getAttribute("puredomlocalstorage"));g&&(j=puredom.json.parse(g));e&&e(j);return j},save:function(a,e,c){var a=this._getKey(a),g=this._getStore(a),j=false;if(g&&"save"in g){e===void 0?g.removeAttribute?g.removeAttribute("puredomlocalstorage"):
g.setAttribute("puredomlocalstorage",""):g.setAttribute("puredomlocalstorage",puredom.json.stringify(e));g.save(a);j=true}c&&c(j);return j},_getStore:function(a){var e;if(!this.stores)this.stores={};e=this.stores[a];if(!e){e=this.stores[a]=document.getElementById(a);if(!e){e=this.stores[a]=document.createElement("span");e.style.position="absolute";e.style.top="-100px";e.style.left="0";e.style.behavior="url('#default#userData')";document.body.appendChild(e)}}if(e.getAttribute("data-tdlsud-loaded")!==
"true"){e.setAttribute("data-tdlsud-loaded","true");e.load(a)}return e},_getKey:function(a){return"ieud"+(a.id||this.defaultName||"")+""}});
puredom.LocalStorage.addAdapter("LocalStorage",{defaultName:"db",rating:60,test:function(){var a="localStorage"in window&&typeof window.localStorage.hasOwnProperty==="function",e,c=puredom.json({a:"a",b:4/3,c:true,d:null});if(a)try{e=localStorage.__test;localStorage.__test=c;localStorage.__test!==c&&(a=false);localStorage.__test=e;e===void 0&&delete localStorage.__test}catch(g){a=false}return a},load:function(a,e){var c=this._getKey(a),g;localStorage.hasOwnProperty(c)&&(g=puredom.json.parse(localStorage[c]));
e&&e(g);return g},save:function(a,e,c){a=this._getKey(a);e===void 0?delete localStorage[a]:localStorage[a]=puredom.json.stringify(e);c&&c(true);return true},_getKey:function(a){return(a.id||this.defaultName||"")+""}});
puredom.LocalStorage.addAdapter("cookie",{defaultName:"db",rating:0,test:function(){return puredom.cookies&&puredom.cookies.get&&"cookie"in document?true:false},load:function(a,e){var c=puredom.cookies.get(a.id||this.defaultName),g;c&&(g=puredom.json(c));e&&e(g);return g},save:function(a,e,c){puredom.cookies.set(a.id||this.defaultName,puredom.json(e));c&&c(true)}});